Repository HandyBus/handybus-web-latest, pull requests merged in 2025-03, with the labels that each got.

#363 release
  src/app/(home)/@reservation/components/Route.tsx
  src/app/mypage/shuttle/[id]/components/sections/ReservationInfoSection.tsx
  src/app/mypage/shuttle/utils/refund.util.ts
  src/app/reservation/[id]/components/BottomBar.tsx
  src/app/reservation/[id]/write/components/steps/payment-step/ReservationInfo.tsx
  src/app/reservation/[id]/write/utils/calculateDDayOnBooking.util.ts
  src/utils/common.util.ts
  src/utils/dateString.util.ts
Labels: release

#366 release
  src/app/auth/login/[oauth]/page.tsx
  src/app/demand/[id]/components/BottomBar.tsx
  src/app/demand/[id]/write/components/WriteForm.tsx
  src/app/mypage/leave/page.tsx
  src/app/mypage/profile/edit/components/EditForm.tsx
  src/app/mypage/reviews/write/[id]/page.tsx
  src/app/mypage/shuttle/[id]/components/sections/HandySection.tsx
  src/app/mypage/shuttle/[id]/handy/page.tsx
  src/app/onboarding/components/OnboardingFunnel.tsx
  src/app/reservation/[id]/components/BottomBar.tsx
  src/app/reservation/[id]/write/components/steps/PassengerInfoStep.tsx
  src/app/reservation/[id]/write/components/steps/RouteSelectStep.tsx
  src/app/reservation/[id]/write/components/steps/payment-step/TossPayments.tsx
  src/components/onboarding-contents/ProfileInfoContent.tsx
  src/components/select/Select.tsx
  src/components/toast-container/ToastContainer.css
  src/hooks/useShare.ts
  src/services/coupon.service.ts
  src/services/demand.service.ts
  src/services/payment.service.ts
  src/services/reservation.service.ts
  src/services/review.service.ts
  src/services/shuttleRoute.service.ts
Labels: release

#369 feat: 왕복행만 핸디를 선택할 수 있게 변경
  src/app/reservation/[id]/write/components/steps/payment-step/ApplyHandy.tsx
Labels: ✨ feature

#372 fix: 약관을 온보딩에서 생략 및 마케팅 수신 동의 수정 구현
  src/app/(home)/@greeting/icons/check.svg
  src/app/(home)/@greeting/icons/first-signup-coupon.svg
  src/app/(home)/@greeting/page.tsx
  src/app/(home)/@onboarding/page.tsx
  src/app/(home)/layout.tsx
  src/app/auth/login/[oauth]/page.tsx
  src/app/login/icons/logo.svg
  src/app/login/page.tsx
  src/app/mypage/leave/page.tsx
  src/app/mypage/profile/edit/marketing/page.tsx
  src/app/mypage/profile/page.tsx
  src/app/onboarding/components/OnboardingFunnel.tsx
  src/app/onboarding/components/bottom-sheets/MarketingBottomSheet.tsx
  src/app/onboarding/components/steps/PersonalInfoStep.tsx
  src/app/onboarding/page.tsx
  src/app/policy/page.tsx
  src/components/header/Header.tsx
  src/components/loading/DeferredSuspense.tsx
  src/types/user.type.ts
  src/utils/localStorage.ts
Labels: 🐛 fix

#373 fix: 왕복 잔여석이 존재 시 추가 셔틀 요청하기 버튼 숨김 처리
  src/app/reservation/[id]/write/components/steps/RouteSelectStep.tsx
  src/components/select/Select.tsx
Labels: 🐛 fix

#374 release
  .github/workflows/pr-labeler.yml
  src/app/(home)/@greeting/icons/check.svg
  src/app/(home)/@greeting/icons/first-signup-coupon.svg
  src/app/(home)/@greeting/page.tsx
  src/app/(home)/@onboarding/page.tsx
  src/app/(home)/layout.tsx
  src/app/auth/login/[oauth]/page.tsx
  src/app/login/icons/logo.svg
  src/app/login/page.tsx
  src/app/mypage/leave/page.tsx
  src/app/mypage/profile/edit/marketing/page.tsx
  src/app/mypage/profile/page.tsx
  src/app/onboarding/components/OnboardingFunnel.tsx
  src/app/onboarding/components/bottom-sheets/MarketingBottomSheet.tsx
  src/app/onboarding/components/steps/PersonalInfoStep.tsx
  src/app/onboarding/page.tsx
  src/app/policy/page.tsx
  src/app/reservation/[id]/write/components/steps/RouteSelectStep.tsx
  src/app/reservation/[id]/write/components/steps/payment-step/ApplyHandy.tsx
  src/components/header/Header.tsx
  src/components/loading/DeferredSuspense.tsx
  src/components/select/Select.tsx
  src/data/faq/6-threshold.mdx
  src/data/faq/index.tsx
  src/types/user.type.ts
  src/utils/localStorage.ts
Labels: 🔖 release

#376 feat: 홈페이지 전체보기 개선
  src/app/(home)/@bot/components/Overviews.tsx
  src/app/(home)/@bot/components/PromotionReviews.tsx
  src/app/(home)/@demand/components/DemandView.tsx
  src/app/(home)/@demand/page.tsx
  src/app/(home)/@reservation/page.tsx
  src/app/help/about/components/AboutMerit.tsx
  src/app/help/about/components/AboutService.tsx
  src/app/help/about/components/AboutStats.tsx
  src/app/help/faq/page.tsx
  src/app/help/how-to/page.tsx
  src/components/article/Article.tsx
Labels: ✨ feat

#377 release
  .github/workflows/pr-labeler.yml
  src/app/(home)/@bot/components/Overviews.tsx
  src/app/(home)/@bot/components/PromotionReviews.tsx
  src/app/(home)/@demand/components/DemandView.tsx
  src/app/(home)/@demand/page.tsx
  src/app/(home)/@reservation/page.tsx
  src/app/help/about/components/AboutMerit.tsx
  src/app/help/about/components/AboutService.tsx
  src/app/help/about/components/AboutStats.tsx
  src/app/help/faq/page.tsx
  src/app/help/how-to/page.tsx
  src/components/article/Article.tsx
  src/data/faq/index.tsx
Labels: 🔖 release

#379 feat: faq 리스트 업데이트
  src/app/help/faq/components/FAQ.tsx
  src/data/faq/1-sure.mdx
  src/data/faq/2-change.mdx
  src/data/faq/3-refund.mdx
  src/data/faq/4-stop.mdx
  src/data/faq/5-no.mdx
  src/data/faq/6-threshold.mdx
  src/data/faq/7-bus.mdx
  src/data/faq/boarding-1-does-shuttle-stop-at-rest-area.mdx
  src/data/faq/boarding-2-what-bus-is-used-for-service.mdx
  src/data/faq/boarding-3-how-are-seats-assigned.mdx
  src/data/faq/boarding-4-leave-luggage-on-shuttle.mdx
  src/data/faq/boarding-5-change-one-way-to-round-trip.mdx
  src/data/faq/boarding-6-use-one-way-from-round-trip.mdx
  src/data/faq/etc-1-did-not-receive-signup-coupon.mdx
  src/data/faq/etc-2-what-is-handy.mdx
  src/data/faq/index.tsx
  src/data/faq/reservation-1-what-is-demand.mdx
  src/data/faq/reservation-2-when-can-i-book.mdx
  src/data/faq/reservation-3-how-many-people-needed-for-survey.mdx
  src/data/faq/reservation-4-no-desired-stop-in-survey.mdx
  src/data/faq/reservation-5-when-is-shuttle-confirmed.mdx
  src/data/faq/reservation-6-sold-out-additional-shuttle.mdx
  src/data/faq/reservation-7-check-reservation-details.mdx
  src/data/faq/reservation-8-change-boarding-location.mdx
  src/data/faq/reservation-9-cancel-reservation.mdx
Labels: ✨ feat

#380 release: v1
  src/app/help/faq/components/FAQ.tsx
  src/data/faq/1-sure.mdx
  src/data/faq/2-change.mdx
  src/data/faq/3-refund.mdx
  src/data/faq/4-stop.mdx
  src/data/faq/5-no.mdx
  src/data/faq/6-threshold.mdx
  src/data/faq/7-bus.mdx
  src/data/faq/boarding-1-does-shuttle-stop-at-rest-area.mdx
  src/data/faq/boarding-2-what-bus-is-used-for-service.mdx
  src/data/faq/boarding-3-how-are-seats-assigned.mdx
  src/data/faq/boarding-4-leave-luggage-on-shuttle.mdx
  src/data/faq/boarding-5-change-one-way-to-round-trip.mdx
  src/data/faq/boarding-6-use-one-way-from-round-trip.mdx
  src/data/faq/etc-1-did-not-receive-signup-coupon.mdx
  src/data/faq/etc-2-what-is-handy.mdx
  src/data/faq/index.tsx
  src/data/faq/reservation-1-what-is-demand.mdx
  src/data/faq/reservation-2-when-can-i-book.mdx
  src/data/faq/reservation-3-how-many-people-needed-for-survey.mdx
  src/data/faq/reservation-4-no-desired-stop-in-survey.mdx
  src/data/faq/reservation-5-when-is-shuttle-confirmed.mdx
  src/data/faq/reservation-6-sold-out-additional-shuttle.mdx
  src/data/faq/reservation-7-check-reservation-details.mdx
  src/data/faq/reservation-8-change-boarding-location.mdx
  src/data/faq/reservation-9-cancel-reservation.mdx
Labels: 🔖 release

#382 feat: 마이페이지에서 핸디 지원 불가 처리
  src/app/mypage/shuttle/[id]/components/sections/HandySection.tsx
  src/app/mypage/shuttle/[id]/page.tsx
Labels: 🔥 hotfix

#387 release: v1
  src/services/hub.service.ts
Labels: 🔖 release

#385 feat: 행사 상세 페이지 마크업 및 form 바텀시트 네비게이션
  public/icons/info.svg
  src/app/event/[eventId]/components/BottomBar.tsx
  src/app/event/[eventId]/components/DateButton.tsx
  src/app/event/[eventId]/components/EventForm.tsx
  src/app/event/[eventId]/components/EventGuidelines.tsx
  src/app/event/[eventId]/components/EventImage.tsx
  src/app/event/[eventId]/components/EventInfo.tsx
  src/app/event/[eventId]/components/HubButton.tsx
  src/app/event/[eventId]/components/RequestSeatAlarmButton.tsx
  src/app/event/[eventId]/components/SidoButton.tsx
  src/app/event/[eventId]/components/SimpleRouteInfo.tsx
  src/app/event/[eventId]/components/steps/common-steps/CommonDateStep.tsx
  src/app/event/[eventId]/components/steps/common-steps/CommonSidoStep.tsx
  src/app/event/[eventId]/components/steps/demand-steps/DemandHubInfoStep.tsx
  src/app/event/[eventId]/components/steps/demand-steps/DemandHubsStep.tsx
  src/app/event/[eventId]/components/steps/demand-steps/DemandTripTypeStep.tsx
  src/app/event/[eventId]/components/steps/extra-steps/ExtraDuplicateHubStep.tsx
  src/app/event/[eventId]/components/steps/extra-steps/ExtraOpenSidoStep.tsx
  src/app/event/[eventId]/components/steps/extra-steps/ExtraSeatAlarmStep.tsx
  src/app/event/[eventId]/components/steps/extra-steps/ExtraSidoInfoStep.tsx
  src/app/event/[eventId]/components/steps/reservation-steps/ReservationHubsStep.tsx
  src/app/event/[eventId]/components/steps/reservation-steps/ReservationInfoStep.tsx
  src/app/event/[eventId]/components/steps/reservation-steps/ReservationTripTypeStep.tsx
  src/app/event/[eventId]/form.const.ts
  src/app/event/[eventId]/icons/add.svg
  src/app/event/[eventId]/icons/calendar.svg
  src/app/event/[eventId]/icons/chevron-down.svg
  src/app/event/[eventId]/icons/dot-primary.svg
  src/app/event/[eventId]/icons/dot-tertiary.svg
  src/app/event/[eventId]/icons/notification.svg
  src/app/event/[eventId]/icons/pin-primary.svg
  src/app/event/[eventId]/icons/pin-small.svg
  src/app/event/[eventId]/icons/pin.svg
  src/app/event/[eventId]/icons/subtract.svg
  src/app/event/[eventId]/icons/triangle.svg
  src/app/event/[eventId]/mock.const.ts
  src/app/event/[eventId]/page.tsx
  src/app/globals.css
  src/app/mypage/shuttle/[id]/components/sections/RefundGuideSection.tsx
  src/app/mypage/shuttle/components/CancelBottomSheet.tsx
  src/components/accordion/Accordion.tsx
  src/components/accordion/icons/arrow-down.svg
  src/components/badge/Badge.tsx
  src/components/bottom-sheet/BottomSheet.tsx
  src/components/buttons/button/Button.tsx
  src/components/guidelines/Guideline.tsx
  src/components/guidelines/contents/CancellationAndRefund.tsx
  src/components/guidelines/contents/Demand.tsx
  src/components/guidelines/contents/Notice.tsx
  src/components/modals/Modal.tsx
  src/components/notice-section/NoticeSection.tsx
  src/components/tooltip/Tooltip.tsx
  src/constants/regions.ts
  src/utils/dateString.util.ts
Labels: ✨ feat

#388 fix: 결제 약관 미동의 시 에러 처리
  src/app/reservation/[id]/write/components/steps/payment-step/TossPayments.tsx
Labels: 🐛 fix

#389 release
  src/app/reservation/[id]/write/components/steps/payment-step/TossPayments.tsx
Labels: 🔖 release
