Repository HandyBus/handybus-web-latest, pull requests merged in 2025-05, with the labels that each got.

#428 feat: 마이페이지, 프로필 수정 및 환경설정 페이지
  src/app/(home)/@greeting/page.tsx
  src/app/mypage/components/Activity.tsx
  src/app/mypage/components/ListButton.tsx
  src/app/mypage/components/Profile.tsx
  src/app/mypage/components/Settings.tsx
  src/app/mypage/icons/arrow-right.svg
  src/app/mypage/icons/calendar.svg
  src/app/mypage/icons/coupon.svg
  src/app/mypage/icons/review.svg
  src/app/mypage/page.tsx
  src/app/mypage/profile/edit/components/EditForm.tsx
  src/app/mypage/profile/edit/marketing/page.tsx
  src/app/mypage/profile/edit/page.tsx
  src/app/mypage/profile/page.tsx
  src/app/mypage/settings/page.tsx
  src/app/onboarding/components/OnboardingFunnel.tsx
  src/app/onboarding/components/bottom-sheets/MarketingBottomSheet.tsx
  src/app/onboarding/components/bottom-sheets/PersonalInfoBottomSheet.tsx
  src/app/onboarding/components/bottom-sheets/ServiceBottomSheet.tsx
  src/app/onboarding/components/steps/AgreementStep.tsx
  src/app/onboarding/components/steps/ArtistStep.tsx
  src/app/onboarding/components/steps/PersonalInfoStep.tsx
  src/app/onboarding/components/steps/PhoneNumberStep.tsx
  src/app/onboarding/components/steps/ProfileInfoStep.tsx
  src/app/onboarding/components/steps/ResidenceStep.tsx
  src/components/buttons/button/Button.tsx
  src/components/header/UserProfile.tsx
  src/components/inputs/text-input/TextInput.tsx
  src/components/onboarding-contents/ArtistContent.tsx
  src/components/onboarding-contents/OnboardingFrame.tsx
  src/components/onboarding-contents/PersonalInfoContent.tsx
  src/components/onboarding-contents/ProfileInfoContent.tsx
  src/components/onboarding-contents/ResidenceContent.tsx
  src/components/onboarding-contents/formValidation.const.ts
  src/components/onboarding-contents/onboarding.type.ts
  src/constants/common.ts
  src/utils/generateProfileBackgroundColor.ts
Labels: ✨ feat

#425 feat: V2 리뷰 조회
  public/images/review-1-1.png
  public/images/reviews/event-11to12.png
  public/images/reviews/event-13to14.png
  public/images/reviews/event-1to2.png
  public/images/reviews/event-3.png
  public/images/reviews/event-4to5.png
  public/images/reviews/event-6.png
  public/images/reviews/event-7.png
  public/images/reviews/event-8.png
  public/images/reviews/event-9to10.png
  public/images/reviews/review-1-1.png
  public/images/reviews/review-1-2.png
  public/images/reviews/review-10.png
  public/images/reviews/review-11.png
  public/images/reviews/review-12.png
  public/images/reviews/review-13.png
  public/images/reviews/review-14.png
  public/images/reviews/review-9.png
  public/images/reviews/review-banner.png
  src/app/(home)/@bot/components/PromotionReviews.tsx
  src/app/help/reviews/layout.tsx
  src/app/help/reviews/page.tsx
  src/app/mypage/reviews/page.tsx
  src/app/reviews/components/DetailedReview.tsx
  src/app/reviews/components/DetailedStaticReview.tsx
  src/app/reviews/components/ReviewItem.tsx
  src/app/reviews/components/ReviewStatistics.tsx
  src/app/reviews/convertStaticToReviewEntity.util.ts
  src/app/reviews/icons/artist.svg
  src/app/reviews/icons/heart.svg
  src/app/reviews/icons/locate.svg
  src/app/reviews/icons/review.svg
  src/app/reviews/icons/thumbsup.svg
  src/app/reviews/page.tsx
  src/app/reviews/review.const.ts
Labels: ✨ feat

#430 design: home v2 피드백 반영
  package-lock.json
  package.json
  src/app/(home)/@bot/components/Help.tsx
  src/app/(home)/@bot/page.tsx
  src/app/(home)/@event/components/CardSection.tsx
  src/app/(home)/@event/components/EventsSwiperView.tsx
  src/app/(home)/@event/components/TrendShuttleCard.tsx
  src/app/event/components/FilterBar.tsx
  src/app/fonts/dm-sans/DMSans-SemiBold.ttf
  src/app/fonts/dm-sans/font.css
  src/app/layout.tsx
  src/components/card/Card.tsx
  tailwind.config.ts
Labels: 🎨 design

#431 feat: 내 수요조사 및 예약 내역 페이지
  src/app/mypage/components/Activity.tsx
  src/app/mypage/components/Settings.tsx
  src/app/mypage/icons/coupon.svg
  src/app/mypage/icons/list.svg
  src/app/mypage/reviews/write/[id]/page.tsx
  src/app/mypage/shuttle/[id]/page.tsx
  src/app/mypage/shuttle/components/DemandCard.tsx
  src/app/mypage/shuttle/components/EmptyView.tsx
  src/app/mypage/shuttle/components/ReservationCard.tsx
  src/app/mypage/shuttle/components/demands/DemandCard.tsx
  src/app/mypage/shuttle/components/demands/DemandTab.tsx
  src/app/mypage/shuttle/components/demands/EmptyView.tsx
  src/app/mypage/shuttle/components/period-filter-bar/PeriodFilterBar.tsx
  src/app/mypage/shuttle/components/period-filter-bar/hooks/usePeriodFilter.tsx
  src/app/mypage/shuttle/components/reservations/ChatButton.tsx
  src/app/mypage/shuttle/components/reservations/EmptyView.tsx
  src/app/mypage/shuttle/components/reservations/HandyBadge.tsx
  src/app/mypage/shuttle/components/reservations/ReservationTab.tsx
  src/app/mypage/shuttle/components/reservations/ShuttleBusBadge.tsx
  src/app/mypage/shuttle/components/reservations/reservation-card/ReservationCard.tsx
  src/app/mypage/shuttle/components/reservations/reservation-card/hooks/useEventText.ts
  src/app/mypage/shuttle/components/reservations/reservation-card/hooks/useStatus.ts
  src/app/mypage/shuttle/components/reservations/reservation-card/hooks/useTextAndStyle.ts
  src/app/mypage/shuttle/components/tabs/CurrentTab.tsx
  src/app/mypage/shuttle/components/tabs/DemandTab.tsx
  src/app/mypage/shuttle/components/tabs/PastTab.tsx
  src/app/mypage/shuttle/icons/arrow-right.svg
  src/app/mypage/shuttle/icons/calendar-grey.svg
  src/app/mypage/shuttle/page.tsx
  src/app/mypage/shuttle/utils/status.util.ts
  src/components/tab/Tabs.tsx
  src/constants/status.ts
  src/services/demand.service.ts
  src/types/demand.type.ts
Labels: ✨ feat

#429 feat: 공지사항 조회
  package-lock.json
  package.json
  src/app/(home)/@bot/components/AnnouncementPreview.tsx
  src/app/(home)/@bot/components/NoticeBoard.tsx
  src/app/(home)/@bot/page.tsx
  src/app/mypage/announcements/[id]/page.tsx
  src/app/mypage/announcements/components/AnnouncementItem.tsx
  src/app/mypage/announcements/components/AnnouncementList.tsx
  src/app/mypage/announcements/page.tsx
  src/app/mypage/components/Settings.tsx
  src/app/mypage/notice-board/[id]/page.tsx
  src/app/mypage/notice-board/components/NoticeList.tsx
  src/services/core.service.ts
  src/types/announcement.type.ts
Labels: ✨ feat

#432 fix: V1 핸디 지원 버튼 디자인 변경 실험
  src/app/reservation/[id]/write/components/steps/payment-step/ApplyHandy.tsx
Labels: 🐛 fix

#433 release: v1
  src/app/reservation/[id]/write/components/steps/payment-step/ApplyHandy.tsx
Labels: 🔖 release

#435 fix: 캐러셀 렌더링 버그 수정
  src/app/(home)/@event/components/EventsSwiperView.tsx
Labels: 🐛 fix

#436 fix: 캐러셀 카드 extend 로직 수정
  src/app/(home)/@event/components/EventsSwiperView.tsx
Labels: 🐛 fix

#437 feat: 의견 보내기 api 연동
  src/app/event/[eventId]/components/demand-complete-screen/DemandCompleteScreen.tsx
  src/app/event/[eventId]/components/demand-complete-screen/FailScreen.tsx
  src/app/event/[eventId]/components/demand-complete-screen/SuccessScreen.tsx
  src/app/event/[eventId]/dailyevent/[dailyEventId]/route/[shuttleRouteId]/payment/request/[reservationId]/page.tsx
  src/app/event/[eventId]/dailyevent/[dailyEventId]/route/[shuttleRouteId]/payment/request/fail/page.tsx
  src/app/help/faq/page.tsx
  src/components/feedback/FeedbackScreen.tsx
  src/services/core.service.ts
Labels: ✨ feat

#434 feat: 내 예약 상세 조회 페이지 및 관련 기능 구현
  src/app/event/[eventId]/dailyevent/[dailyEventId]/route/[shuttleRouteId]/payment/request/[reservationId]/page.tsx
  src/app/mypage/shuttle/[id]/components/Content.tsx
  src/app/mypage/shuttle/[id]/components/DetailRow.tsx
  src/app/mypage/shuttle/[id]/components/Divider.tsx
  src/app/mypage/shuttle/[id]/components/EventCard.tsx
  src/app/mypage/shuttle/[id]/components/RefundPolicy.tsx
  src/app/mypage/shuttle/[id]/components/Section.tsx
  src/app/mypage/shuttle/[id]/components/WrapperWithDivider.tsx
  src/app/mypage/shuttle/[id]/components/sections/BusInfoSection.tsx
  src/app/mypage/shuttle/[id]/components/sections/GuidelineSection.tsx
  src/app/mypage/shuttle/[id]/components/sections/HandySection.tsx
  src/app/mypage/shuttle/[id]/components/sections/PaymentInfoSection.tsx
  src/app/mypage/shuttle/[id]/components/sections/RefundGuideSection.tsx
  src/app/mypage/shuttle/[id]/components/sections/RefundInfoSection.tsx
  src/app/mypage/shuttle/[id]/components/sections/ReservationInfoSection.tsx
  src/app/mypage/shuttle/[id]/components/sections/ReservationPersonInfoSection.tsx
  src/app/mypage/shuttle/[id]/components/sections/RouteSection.tsx
  src/app/mypage/shuttle/[id]/components/sections/TermsSection.tsx
  src/app/mypage/shuttle/[id]/components/sections/handy-section/HandySection.tsx
  src/app/mypage/shuttle/[id]/components/sections/handy-section/components/CancelHandyApplyModal.tsx
  src/app/mypage/shuttle/[id]/components/sections/handy-section/hooks/useCancelApplyHandy.tsx
  src/app/mypage/shuttle/[id]/components/sections/price-section/PriceSection.tsx
  src/app/mypage/shuttle/[id]/components/sections/price-section/components/RefundPriceContent.tsx
  src/app/mypage/shuttle/[id]/components/sections/price-section/components/RegularPriceContent.tsx
  src/app/mypage/shuttle/[id]/components/sections/price-section/icons/arrow-downward-tip-right.svg
  src/app/mypage/shuttle/[id]/components/sections/refund-section/RefundSection.tsx
  src/app/mypage/shuttle/[id]/components/sections/refund-section/components/CancelBottomSheet.tsx
  src/app/mypage/shuttle/[id]/components/sections/refund-section/utils/refund.util.ts
  src/app/mypage/shuttle/[id]/components/sections/shuttle-info-section/ShuttleInfoSection.tsx
  src/app/mypage/shuttle/[id]/components/sections/shuttle-info-section/components/HubItem.tsx
  src/app/mypage/shuttle/[id]/components/sections/shuttle-info-section/components/TripCard.tsx
  src/app/mypage/shuttle/[id]/components/sections/shuttle-info-section/icons/dot-primary.svg
  src/app/mypage/shuttle/[id]/components/sections/shuttle-info-section/icons/pin-primary.svg
  src/app/mypage/shuttle/[id]/components/sections/shuttle-progress-section/ShuttleProgressSection.tsx
  src/app/mypage/shuttle/[id]/components/sections/shuttle-progress-section/hooks/useText.tsx
  src/app/mypage/shuttle/[id]/handy/page.tsx
  src/app/mypage/shuttle/[id]/icons/icon-check-grey.svg
  src/app/mypage/shuttle/[id]/icons/icon-check-primary.svg
  src/app/mypage/shuttle/[id]/icons/icon-check-thin.svg
  src/app/mypage/shuttle/[id]/page.tsx
  src/app/mypage/shuttle/components/CancelBottomSheet.tsx
  src/app/mypage/shuttle/components/reservations/reservation-card/ReservationCard.tsx
  src/app/mypage/shuttle/components/reservations/reservation-card/components/ChatButton.tsx
  src/app/mypage/shuttle/components/reservations/reservation-card/components/HandyBadge.tsx
  src/app/mypage/shuttle/components/reservations/reservation-card/components/ShuttleBusBadge.tsx
  src/app/mypage/shuttle/components/reservations/reservation-card/components/SubmitOpenChatLinkModal.tsx
  src/app/mypage/shuttle/components/reservations/reservation-card/hooks/useTextAndStyle.ts
  src/app/mypage/shuttle/hooks/useReservationProgress.ts
  src/components/accordion/Accordion.tsx
  src/components/buttons/button/Button.tsx
  src/components/modals/Modal.tsx
  src/services/reservation.service.ts
Labels: ✨ feat

#438 feat: 수요조사 및 예약 내역 기간 필터 api 연동
  src/app/mypage/shuttle/[id]/components/sections/shuttle-info-section/components/HubItem.tsx
  src/app/mypage/shuttle/[id]/components/sections/shuttle-progress-section/ShuttleProgressSection.tsx
  src/app/mypage/shuttle/components/demands/DemandTab.tsx
  src/app/mypage/shuttle/components/period-filter-bar/PeriodFilterBar.tsx
  src/app/mypage/shuttle/components/period-filter-bar/hooks/usePeriodFilter.tsx
  src/app/mypage/shuttle/components/reservations/ReservationTab.tsx
  src/app/mypage/shuttle/components/reservations/reservation-card/components/ChatButton.tsx
  src/components/kakao-map/KakaoMap.tsx
  src/hooks/useShare.tsx
  src/services/demand.service.ts
  src/services/reservation.service.ts
Labels: ✨ feat

#441 feat: 내 수요조사 내역 조회 내부 카드 api 연동
  src/app/mypage/shuttle/components/demands/DemandCard.tsx
  src/constants/status.ts
  src/types/demand.type.ts
Labels: ✨ feat

#442 fix: 신청한 빈자리 알림 요청에 대해 알림 받기 버튼 비활성화 처리
  src/app/event/[eventId]/components/EventForm.tsx
  src/app/event/[eventId]/components/RequestSeatAlarmButton.tsx
  src/app/event/[eventId]/components/steps/extra-steps/ExtraSeatAlarmStep.tsx
  src/app/event/[eventId]/store/userAlertRequestsAtom.ts
  src/components/buttons/button/Button.tsx
  src/services/alertRequest.service.ts
Labels: 🐛 fix

#445 fix: 홈의 행사 캐러셀 api 조건 수정 및 스크롤 이슈 해결
  src/app/(home)/@event/components/CardSection.tsx
  src/app/(home)/@event/components/RecommendedEventCard.tsx
  src/app/(home)/@event/components/RecommendedEventSwiperView.tsx
  src/app/(home)/@event/components/TrendEventCard.tsx
  src/app/(home)/@event/components/TrendEventsSwiperView.tsx
  src/services/event.service.ts
Labels: 🐛 fix

#447 feat: 내 빈자리 알림 요청 내역에서 순서 표시
  src/app/mypage/alert-requests/components/AlertRequestCard.tsx
Labels: ✨ feat

#451 fix: 예약 정책에 따라 취소하기 버튼 비활성화 처리
  src/app/event/[eventId]/components/steps/reservation-steps/ReservationInfoStep.tsx
  src/app/event/[eventId]/dailyevent/[dailyEventId]/route/[shuttleRouteId]/payment/page.tsx
  src/app/event/[eventId]/dailyevent/[dailyEventId]/route/[shuttleRouteId]/payment/payment.const.ts
  src/app/mypage/shuttle/[id]/components/sections/handy-section/HandySection.tsx
  src/app/mypage/shuttle/[id]/components/sections/price-section/components/RefundPriceContent.tsx
  src/app/mypage/shuttle/[id]/components/sections/refund-section/RefundSection.tsx
  src/app/mypage/shuttle/[id]/components/sections/refund-section/components/CancelBottomSheet.tsx
  src/app/mypage/shuttle/[id]/components/sections/refund-section/utils/refund.util.ts
  src/app/mypage/shuttle/hooks/useReservationProgress.ts
Labels: 🐛 fix

#450 fix: event destination을 event location으로 변경
  src/services/hub.service.ts
Labels: 🐛 fix

#453 feat: 첫 가입 감사 쿠폰 삭제
  src/app/(home)/@greeting/icons/first-signup-coupon.svg
  src/app/(home)/@greeting/page.tsx
  src/app/login/page.tsx
  src/data/faq/etc-1-did-not-receive-signup-coupon.mdx
  src/data/faq/etc-1-what-is-handy.mdx
  src/data/faq/index.tsx
Labels: ✨ feat

#454 release: v1
  src/app/(home)/@greeting/icons/first-signup-coupon.svg
  src/app/(home)/@greeting/page.tsx
  src/app/login/page.tsx
  src/data/faq/etc-1-did-not-receive-signup-coupon.mdx
  src/data/faq/etc-1-what-is-handy.mdx
  src/data/faq/index.tsx
Labels: 🔖 release

#460 fix: 행사 전체보기 페이지에서 목데이터만 표시되는 이슈해결
  src/app/event/page.tsx
  src/app/event/toSorted.util.ts
  src/components/card/Card.tsx
Labels: 🐛 fix

#456 feat: 첫 가입 감사 쿠폰 삭제
  src/app/(home)/@greeting/page.tsx
  src/app/help/faq/components/FAQList.tsx
  src/app/help/faq/faqItems.const.ts
  src/components/accordion/Accordion.tsx
  src/data/faq/etc-1-did-not-receive-signup-coupon.mdx
  src/data/faq/etc-1-what-is-handy.mdx
  src/data/faq/index.tsx
Labels: ✨ feat

#455 feat: 리뷰 전체보기 필터 및 통계 api 연동
  src/app/(home)/@bot/components/PromotionReviews.tsx
  src/app/mypage/reviews/[reviewId]/components/FilterButton.tsx
  src/app/mypage/reviews/[reviewId]/components/ReviewListWithMyReview.tsx
  src/app/mypage/reviews/[reviewId]/components/ReviewStatistics.tsx
  src/app/mypage/reviews/[reviewId]/review.const.ts
  src/app/mypage/reviews/edit/[reviewId]/components/ReviewEditForm.tsx
  src/app/mypage/reviews/write/[reservationId]/components/ReviewWriteForm.tsx
  src/app/reviews/components/FilterButton.tsx
  src/app/reviews/components/ReviewList.tsx
  src/app/reviews/components/ReviewStatistics.tsx
  src/app/reviews/convertStaticToReviewEntity.util.ts
  src/app/reviews/review.const.ts
  src/services/review.service.ts
  src/types/review.type.ts
Labels: ✨ feat

#461 fix: 리뷰 전체보기에서 최신순 정렬 반대로 되어있던 이슈 해결
  src/app/mypage/reviews/[reviewId]/components/FilterButton.tsx
  src/app/mypage/reviews/[reviewId]/components/ReviewListWithMyReview.tsx
  src/app/reviews/components/FilterButton.tsx
  src/app/reviews/components/ReviewList.tsx
Labels: 🐛 fix

#458 refactor: 행사 상세 페이지 로직 분리
  src/app/event/[eventId]/components/EventForm.tsx
  src/app/event/[eventId]/components/event-form/EventForm.tsx
  src/app/event/[eventId]/components/event-form/hooks/useAlertFeedBackScreen.tsx
  src/app/event/[eventId]/components/event-form/hooks/useBottomSheetText.tsx
  src/app/event/[eventId]/components/event-form/hooks/useEventInitialization.tsx
  src/app/event/[eventId]/components/event-form/hooks/useHistory.tsx
  src/app/event/[eventId]/components/event-form/hooks/useInputSectionText.tsx
  src/app/event/[eventId]/components/steps/StepComponent.tsx
  src/app/event/[eventId]/page.tsx
Labels: 🔄 refactor

#462 fix: 예약 유의사항 업데이트
  src/components/notice-section/NoticeSection.tsx
Labels: 🐛 fix

#463 release: v1
  src/components/notice-section/NoticeSection.tsx
Labels: 🔖 release

#468 design: 예약 유의사항에 핸디팟 예약마감일 문구 추가
  src/components/notice-section/NoticeSection.tsx
Labels: 🎨 design

#464 design: V1 핸디 가이드 중복 문구 제거
  src/app/help/what-is-handy/page.tsx
Labels: 🎨 design

#465 design: 핸디 소개 문구 중복 제거
  src/app/help/what-is-handy/components/WhatIsHandyContent.tsx
Labels: 🎨 design

#469 hotfix: 행사의 노선이 페이지 이동에 따라 중첩되는 현상 해결
  src/app/event/[eventId]/store/dailyEventIdsWithRoutesAtom.ts
Labels: 🐛 fix, 🔥 hotfix

#476 release: V1
  src/app/reservation/[id]/components/ProductDescription.tsx
  src/app/reservation/[id]/components/ReservationForm.tsx
  src/app/reservation/[id]/components/images/product-desc-bottom.png
  src/app/reservation/[id]/components/images/product-desc-top.png
Labels: 🔖 release

#473 feat: 움직이는 버스 로딩 이미지 구현
  src/app/event/[eventId]/dailyevent/[dailyEventId]/route/[shuttleRouteId]/payment/request/[reservationId]/page.tsx
  src/app/event/[eventId]/dailyevent/[dailyEventId]/route/[shuttleRouteId]/payment/request/icons/bus-fail.svg
  src/app/event/[eventId]/dailyevent/[dailyEventId]/route/[shuttleRouteId]/payment/request/icons/bus-loading.svg
  src/app/event/[eventId]/dailyevent/[dailyEventId]/route/[shuttleRouteId]/payment/request/icons/bus-success.svg
  src/app/event/[eventId]/dailyevent/[dailyEventId]/route/[shuttleRouteId]/payment/request/icons/bus.svg
  src/app/event/[eventId]/dailyevent/[dailyEventId]/route/[shuttleRouteId]/payment/request/icons/road.svg
  src/app/event/[eventId]/dailyevent/[dailyEventId]/route/[shuttleRouteId]/payment/request/page.tsx
  tailwind.config.ts
Labels: ✨ feat

#486 fix: 내 후기 버그 수정 및 피드백 반영
  src/app/mypage/reviews/components/WritableReviews.tsx
  src/app/mypage/reviews/components/reservation-card/ReviewButton.tsx
  src/app/mypage/reviews/write/[reservationId]/page.tsx
Labels: 🐛 fix

#483 design: 홈 UI 피드백을 반영
  src/app/(home)/@event/components/CardSection.tsx
  src/app/(home)/@event/components/ViewAllButton.tsx
  src/app/event/components/Empty.tsx
  src/app/event/components/Error.tsx
  src/app/event/components/Loading.tsx
  src/app/event/page.tsx
  src/components/article/Article.tsx
Labels: 🎨 design

#484 fix: 열린 셔틀 보기로 입장 시 수요조사가 다른 지역으로 뜨던 현상 해결
  src/app/event/[eventId]/components/steps/demand-steps/DemandHubsStep.tsx
  src/app/event/[eventId]/components/steps/extra-steps/ExtraSidoInfoStep.tsx
Labels: 🐛 fix

#485 fix: 핸디 가이드 링크 수정
  src/app/mypage/shuttle/components/reservations/reservation-card/components/ChatButton.tsx
Labels: 🐛 fix

#492 fix: trip type 순서를 왕복을 마지막으로 변경
  src/app/reservation/[id]/components/PriceStats.tsx
  src/app/reservation/[id]/write/components/steps/RouteSelectStep.tsx
  src/types/shuttleRoute.type.ts
Labels: 🐛 fix

#493 release: V1
  src/app/reservation/[id]/components/PriceStats.tsx
  src/app/reservation/[id]/write/components/steps/RouteSelectStep.tsx
  src/types/shuttleRoute.type.ts
Labels: 🔖 release
