Repository HandyBus/handybus-web-latest, pull requests merged in 2025-04, with the labels that each got.

#390 feat: v2 header
  public/icons/logo-v2.svg
  src/components/header/Header.tsx
  src/components/header/UserProfile.tsx
Labels: ✨ feat

#394 feat: 리뷰 글자 수 제한
  src/app/mypage/reviews/write/[id]/page.tsx
  src/app/mypage/shuttle/components/tabs/PastTab.tsx
Labels: ✨ feat

#391 feat: 정류장 기반 수요조사 및 예약 바텀시트 form
  package-lock.json
  package.json
  src/app/event/[eventId]/components/BottomBar.tsx
  src/app/event/[eventId]/components/EventForm.tsx
  src/app/event/[eventId]/components/EventInfo.tsx
  src/app/event/[eventId]/components/RequestSeatAlarmButton.tsx
  src/app/event/[eventId]/components/SimpleRouteInfo.tsx
  src/app/event/[eventId]/components/demand-complete-screen/DemandCompleteScreen.tsx
  src/app/event/[eventId]/components/demand-complete-screen/FailScreen.tsx
  src/app/event/[eventId]/components/demand-complete-screen/FeedbackScreen.tsx
  src/app/event/[eventId]/components/demand-complete-screen/SuccessScreen.tsx
  src/app/event/[eventId]/components/steps/common-steps/CommonDateStep.tsx
  src/app/event/[eventId]/components/steps/common-steps/CommonSidoStep.tsx
  src/app/event/[eventId]/components/steps/demand-steps/DemandHubInfoStep.tsx
  src/app/event/[eventId]/components/steps/demand-steps/DemandHubsStep.tsx
  src/app/event/[eventId]/components/steps/demand-steps/DemandTripTypeStep.tsx
  src/app/event/[eventId]/components/steps/extra-steps/ExtraDuplicateHubStep.tsx
  src/app/event/[eventId]/components/steps/extra-steps/ExtraHubsInRouteStep.tsx
  src/app/event/[eventId]/components/steps/extra-steps/ExtraOpenSidoStep.tsx
  src/app/event/[eventId]/components/steps/extra-steps/ExtraSeatAlarmStep.tsx
  src/app/event/[eventId]/components/steps/extra-steps/ExtraSidoInfoStep.tsx
  src/app/event/[eventId]/components/steps/extra-steps/ExtraUnreservableRegionStep.tsx
  src/app/event/[eventId]/components/steps/reservation-steps/ReservationHubsStep.tsx
  src/app/event/[eventId]/components/steps/reservation-steps/ReservationInfoStep.tsx
  src/app/event/[eventId]/components/steps/reservation-steps/ReservationTripTypeStep.tsx
  src/app/event/[eventId]/event.util.ts
  src/app/event/[eventId]/form.const.tsx
  src/app/event/[eventId]/form.type.ts
  src/app/event/[eventId]/icons/add.svg
  src/app/event/[eventId]/icons/arrow-right.svg
  src/app/event/[eventId]/icons/demand-fail.svg
  src/app/event/[eventId]/icons/demand-success.svg
  src/app/event/[eventId]/icons/subtract.svg
  src/app/event/[eventId]/images/demand-fail.png
  src/app/event/[eventId]/images/demand-success.png
  src/app/event/[eventId]/mock.const.ts
  src/app/event/[eventId]/page.tsx
  src/app/event/[eventId]/store/dailyEventIdsWithHubsAtom.ts
  src/app/event/[eventId]/store/dailyEventIdsWithRoutesAtom.ts
  src/app/event/[eventId]/store/eventAtom.ts
  src/app/event/[eventId]/store/userDemandsAtom.tsx
  src/app/login/page.tsx
  src/app/mypage/shuttle/components/tabs/DemandTab.tsx
  src/components/Provider.tsx
  src/components/buttons/button/Button.tsx
  src/constants/common.ts
  src/hooks/useAuthRouter.ts
  src/services/demand.service.ts
  src/services/event.service.ts
  src/services/hub.service.ts
  src/services/shuttleRoute.service.ts
  src/types/common.type.ts
  src/types/demand.type.ts
  src/types/event.type.ts
  src/types/shuttleRoute.type.ts
  src/utils/searchParams.util.ts
Labels: ✨ feat

#395 release: v1
  src/app/mypage/reviews/write/[id]/page.tsx
  src/app/mypage/shuttle/components/tabs/PastTab.tsx
Labels: 🔖 release

#393 feat: 행사 공유하기
  src/app/event/[eventId]/components/BottomBar.tsx
  src/app/event/[eventId]/components/EventForm.tsx
  src/app/event/[eventId]/components/ShareBottomSheet.tsx
  src/app/event/[eventId]/icons/kakao.svg
  src/app/event/[eventId]/icons/link.svg
  src/app/event/[eventId]/icons/x.svg
  src/app/event/[eventId]/images/demand-fail.png
  src/app/event/[eventId]/images/demand-success.png
  src/components/bottom-sheet/share-sheet/ShareSheet.tsx
  src/hooks/useBottomSheet.tsx
  src/hooks/useShare.tsx
Labels: ✨ feat

#397 chore: 재병합
  src/app/event/[eventId]/components/BottomBar.tsx
  src/app/event/[eventId]/components/EventForm.tsx
  src/app/event/[eventId]/components/ShareBottomSheet.tsx
  src/app/event/[eventId]/icons/kakao.svg
  src/app/event/[eventId]/icons/link.svg
  src/app/event/[eventId]/icons/x.svg
  src/app/event/[eventId]/images/demand-fail.png
  src/app/event/[eventId]/images/demand-success.png
  src/components/bottom-sheet/share-sheet/ShareSheet.tsx
  src/hooks/useBottomSheet.tsx
  src/hooks/useShare.tsx
Labels: 🧹 chore

#399 release: v1
  src/components/notice-section/NoticeSection.tsx
Labels: 🔖 release

#401 fix: 행사 상세 페이지 디자인 QA 반영
  src/app/event/[eventId]/components/BottomBar.tsx
  src/app/event/[eventId]/components/DateButton.tsx
  src/app/event/[eventId]/components/EventForm.tsx
  src/app/event/[eventId]/components/EventImage.tsx
  src/app/event/[eventId]/components/HubButton.tsx
  src/app/event/[eventId]/components/SidoButton.tsx
  src/app/event/[eventId]/components/SimpleRouteInfo.tsx
  src/app/event/[eventId]/components/steps/common-steps/CommonDateStep.tsx
  src/app/event/[eventId]/components/steps/common-steps/CommonSidoStep.tsx
  src/app/event/[eventId]/components/steps/demand-steps/DemandHubsStep.tsx
  src/app/event/[eventId]/components/steps/demand-steps/DemandTripTypeStep.tsx
  src/app/event/[eventId]/components/steps/extra-steps/ExtraDuplicateHubStep.tsx
  src/app/event/[eventId]/components/steps/extra-steps/ExtraUnreservableRegionStep.tsx
  src/app/event/[eventId]/components/steps/reservation-steps/ReservationHubsStep.tsx
  src/app/event/[eventId]/components/steps/reservation-steps/ReservationTripTypeStep.tsx
  src/app/event/[eventId]/form.const.tsx
  src/app/event/[eventId]/icons/kakao.svg
  src/app/event/[eventId]/icons/pin-small.svg
  src/components/guidelines/contents/CancellationAndRefund.tsx
Labels: 🐛 fix

#403 fix: 이용약관, FAQ 항목 업데이트
  src/components/notice-section/NoticeSection.tsx
  src/data/faq/boarding-4-leave-luggage-on-shuttle.mdx
  src/data/faq/boarding-5-change-one-way-to-round-trip.mdx
  src/data/faq/boarding-6-use-one-way-from-round-trip.mdx
  src/data/faq/etc-1-did-not-receive-signup-coupon.mdx
  src/data/faq/etc-2-what-is-handy.mdx
  src/data/faq/reservation-1-what-is-demand.mdx
  src/data/faq/reservation-2-when-can-i-book.mdx
  src/data/faq/reservation-4-no-desired-stop-in-survey.mdx
  src/data/faq/reservation-6-sold-out-additional-shuttle.mdx
  src/data/faq/reservation-9-cancel-reservation.mdx
Labels: 🐛 fix

#404 release: v1
  src/components/notice-section/NoticeSection.tsx
  src/data/faq/boarding-4-leave-luggage-on-shuttle.mdx
  src/data/faq/boarding-5-change-one-way-to-round-trip.mdx
  src/data/faq/boarding-6-use-one-way-from-round-trip.mdx
  src/data/faq/etc-1-did-not-receive-signup-coupon.mdx
  src/data/faq/etc-2-what-is-handy.mdx
  src/data/faq/reservation-1-what-is-demand.mdx
  src/data/faq/reservation-2-when-can-i-book.mdx
  src/data/faq/reservation-4-no-desired-stop-in-survey.mdx
  src/data/faq/reservation-6-sold-out-additional-shuttle.mdx
  src/data/faq/reservation-9-cancel-reservation.mdx
Labels: 🔖 release

#402 feat: v2 결제 페이지 마크업
  src/app/event/[eventId]/daily-event/[dailyEventId]/shuttle-route/[shuttleRouteId]/payment/components/BottomBar.tsx
  src/app/event/[eventId]/daily-event/[dailyEventId]/shuttle-route/[shuttleRouteId]/payment/components/Divider.tsx
  src/app/event/[eventId]/daily-event/[dailyEventId]/shuttle-route/[shuttleRouteId]/payment/components/Section.tsx
  src/app/event/[eventId]/daily-event/[dailyEventId]/shuttle-route/[shuttleRouteId]/payment/components/sections/ClientInfoSection.tsx
  src/app/event/[eventId]/daily-event/[dailyEventId]/shuttle-route/[shuttleRouteId]/payment/components/sections/CouponSection.tsx
  src/app/event/[eventId]/daily-event/[dailyEventId]/shuttle-route/[shuttleRouteId]/payment/components/sections/EventInfoSection.tsx
  src/app/event/[eventId]/daily-event/[dailyEventId]/shuttle-route/[shuttleRouteId]/payment/components/sections/HandySection.tsx
  src/app/event/[eventId]/daily-event/[dailyEventId]/shuttle-route/[shuttleRouteId]/payment/components/sections/PaymentSection.tsx
  src/app/event/[eventId]/daily-event/[dailyEventId]/shuttle-route/[shuttleRouteId]/payment/components/sections/PriceSection.tsx
  src/app/event/[eventId]/daily-event/[dailyEventId]/shuttle-route/[shuttleRouteId]/payment/components/sections/ShuttleRouteInfoSection.tsx
  src/app/event/[eventId]/daily-event/[dailyEventId]/shuttle-route/[shuttleRouteId]/payment/icons/arrow-downward-tip-right.svg
  src/app/event/[eventId]/daily-event/[dailyEventId]/shuttle-route/[shuttleRouteId]/payment/icons/arrow-right.svg
  src/app/event/[eventId]/daily-event/[dailyEventId]/shuttle-route/[shuttleRouteId]/payment/icons/dot-primary.svg
  src/app/event/[eventId]/daily-event/[dailyEventId]/shuttle-route/[shuttleRouteId]/payment/icons/pin-primary.svg
  src/app/event/[eventId]/daily-event/[dailyEventId]/shuttle-route/[shuttleRouteId]/payment/page.tsx
Labels: ✨ feat

#409 release: v1
  src/app/reservation/[id]/write/components/steps/payment-step/TossPayments.tsx
Labels: 🔖 release

#412 fix: 로그인 되었을 때에만 헤더에서 유저 정보를 불러오도록 수정
  src/components/header/Header.tsx
Labels: 🐛 fix

#406 feat: 고객센터 페이지 (faq, 약관) 및 Accordion 컴포넌트 title props 수정
  src/app/help/faq/components/FAQ.tsx
  src/app/help/faq/components/FAQList.tsx
  src/app/help/faq/components/TitledSection.tsx
  src/app/help/faq/direct-inquiry/page.tsx
  src/app/help/faq/faqItems.const.ts
  src/app/help/faq/icons/arrow-down.svg
  src/app/help/faq/icons/faq-chevron-up.svg
  src/app/help/faq/icons/faq-handy-logo.svg
  src/app/help/faq/marketing-consent/page.tsx
  src/app/help/faq/page.tsx
  src/app/help/faq/privacy-policy/page.tsx
  src/app/help/faq/terms-of-service/page.tsx
  src/app/policy/page.tsx
  src/components/accordion/Accordion.stories.tsx
  src/components/accordion/Accordion.tsx
  src/components/article/Article.tsx
  src/components/article/ArticleV1.tsx
  src/components/footer/Footer.tsx
  src/components/policy/PolicyViewer.tsx
  src/data/faq/1-sure.mdx
  src/data/faq/2-change.mdx
  src/data/faq/3-refund.mdx
  src/data/faq/4-stop.mdx
  src/data/faq/5-no.mdx
  src/data/faq/6-threshold.mdx
  src/data/faq/7-bus.mdx
  src/data/faq/boarding-1-does-shuttle-stop-at-rest-area.mdx
  src/data/faq/boarding-2-what-bus-is-used-for-service.mdx
  src/data/faq/boarding-3-how-are-seats-assigned.mdx
  src/data/faq/boarding-4-leave-luggage-on-shuttle.mdx
  src/data/faq/boarding-5-change-one-way-to-round-trip.mdx
  src/data/faq/boarding-6-use-one-way-from-round-trip.mdx
  src/data/faq/etc-1-did-not-receive-signup-coupon.mdx
  src/data/faq/etc-2-what-is-handy.mdx
  src/data/faq/index.tsx
  src/data/faq/reservation-1-what-is-demand.mdx
  src/data/faq/reservation-2-when-can-i-book.mdx
  src/data/faq/reservation-3-how-many-people-needed-for-survey.mdx
  src/data/faq/reservation-4-no-desired-stop-in-survey.mdx
  src/data/faq/reservation-5-when-is-shuttle-confirmed.mdx
  src/data/faq/reservation-6-sold-out-additional-shuttle.mdx
  src/data/faq/reservation-7-check-reservation-details.mdx
  src/data/faq/reservation-8-change-boarding-location.mdx
  src/data/faq/reservation-9-cancel-reservation.mdx
  src/data/policy/marketing.mdx
  src/data/policy/privacy.mdx
  src/data/policy/service.mdx
Labels: ✨ feat

#407 feat: v2 핸디버스 가이드 페이지
  src/app/(home)/@bot/components/Help.tsx
  src/app/help/handybus-guide/images/handybus-guide-step-1.png
  src/app/help/handybus-guide/images/handybus-guide-step-2.png
  src/app/help/handybus-guide/images/handybus-guide-step-3.png
  src/app/help/handybus-guide/images/handybus-guide-step-4.png
  src/app/help/handybus-guide/images/handybus-guide-step-5.png
  src/app/help/handybus-guide/images/handybus-guide-step-6.png
  src/app/help/handybus-guide/images/handybus-guide.png
  src/app/help/handybus-guide/page.tsx
  src/components/buttons/button/Button.stories.tsx
Labels: ✨ feat

#415 fix: 204 에서 response body를 기대하여 에러를 던지는 이슈 해결
  src/services/config.ts
Labels: 🐛 fix

#417 hotfix: config에서 204 status code 대응
  src/services/config.ts
Labels: 🐛 fix, 🔥 hotfix

#418 release: v1
  src/services/config.ts
Labels: 🔖 release

#420 hotfix: login page coupon amount
  src/app/login/page.tsx
Labels: 🔥 hotfix

#421 release: V1
  src/app/login/page.tsx
Labels: 🔖 release

#423 fix: 홈페이지 하단 핸디버스 소개 배너 이미지 변경 및 이용절차 페이지 업데이트
  src/app/(home)/@bot/components/Overviews.tsx
  src/app/(home)/@bot/images/2-intro.png
  src/app/help/how-to/images/how-to.png
  src/app/help/how-to/page.tsx
Labels: 🐛 fix

#424 release: V1
  src/app/(home)/@bot/components/Overviews.tsx
  src/app/(home)/@bot/images/2-intro.png
  src/app/help/how-to/images/how-to.png
  src/app/help/how-to/page.tsx
Labels: 🔖 release

#422 feat: 공지사항 마크업
  src/app/mypage/components/Settings.tsx
  src/app/mypage/notice-board/[id]/page.tsx
  src/app/mypage/notice-board/components/NoticeItem.tsx
  src/app/mypage/notice-board/components/NoticeList.tsx
  src/app/mypage/notice-board/page.tsx
Labels: ✨ feat

#405 feat: 행사 전체보기
  public/icons/event-empty.svg
  public/icons/order.svg
  src/app/(home)/@event/components/EventsSwiperView.tsx
  src/app/(home)/@event/components/RecommendedEventCard.tsx
  src/app/(home)/@event/components/TrendShuttleCard.tsx
  src/app/(home)/@event/components/ViewAllButton.tsx
  src/app/(home)/@event/mockData.const.ts
  src/app/(home)/@event/page.tsx
  src/app/event/components/Empty.tsx
  src/app/event/components/FilterBar.tsx
  src/app/event/components/FilterButton.tsx
  src/app/event/event.const.ts
  src/app/event/page.tsx
  src/components/buttons/view-all-button/ViewAllButton.stories.tsx
  src/components/buttons/view-all-button/ViewAllButton.tsx
  src/components/card/Card.tsx
  src/components/chips/Chip.tsx
Labels: ✨ feat

#426 design: 결제 진행 중, 성공, 실패 페이지
  src/app/event/[eventId]/components/FeedbackScreen.tsx
  src/app/event/[eventId]/components/ShareBottomSheet.tsx
  src/app/event/[eventId]/components/demand-complete-screen/DemandCompleteScreen.tsx
  src/app/event/[eventId]/components/demand-complete-screen/FailScreen.tsx
  src/app/event/[eventId]/components/demand-complete-screen/SuccessScreen.tsx
  src/app/event/[eventId]/dailyevent/[dailyEventId]/route/[shuttleRouteId]/payment/request/[reservationId]/page.tsx
  src/app/event/[eventId]/dailyevent/[dailyEventId]/route/[shuttleRouteId]/payment/request/fail/page.tsx
  src/app/event/[eventId]/dailyevent/[dailyEventId]/route/[shuttleRouteId]/payment/request/icons/bus-fail.svg
  src/app/event/[eventId]/dailyevent/[dailyEventId]/route/[shuttleRouteId]/payment/request/icons/bus-loading.svg
  src/app/event/[eventId]/dailyevent/[dailyEventId]/route/[shuttleRouteId]/payment/request/icons/bus-success.svg
  src/app/event/[eventId]/dailyevent/[dailyEventId]/route/[shuttleRouteId]/payment/request/page.tsx
  src/data/faq/reservation-6-sold-out-additional-shuttle.mdx
Labels: 🎨 design
