Repository HandyBus/handybus-web-latest, pull requests merged in 2025-06, with the labels that each got.

#494 fix: 택시 정류장 보여주지 않도록 처리
  src/app/demand/[id]/write/components/JourneyLocationPicker.tsx
Labels: 🐛 fix

#490 design: UI 피드백 반영
  public/icons/event-loading.svg
  public/icons/schedule.svg
  src/app/event/components/Loading.tsx
  src/app/event/page.tsx
  src/app/help/faq/components/FAQList.tsx
  src/app/help/faq/page.tsx
  src/app/help/what-is-handy/components/WhatIsHandyContent.tsx
  src/app/login/page.tsx
  src/app/mypage/alert-requests/components/EmptyView.tsx
  src/app/mypage/alert-requests/icons/alarm.svg
  src/app/mypage/components/Settings.tsx
  src/app/mypage/coupons/components/CouponList.tsx
  src/app/mypage/reviews/[reviewId]/components/ReviewItem.tsx
  src/app/mypage/reviews/[reviewId]/components/ReviewStatistics.tsx
  src/app/mypage/reviews/components/EmptyReview.tsx
  src/app/mypage/reviews/components/review-form/icons/thumbs-up.svg
  src/app/mypage/reviews/edit/[reviewId]/components/ReviewEditForm.tsx
  src/app/mypage/reviews/icons/icon-reviews.svg
  src/app/mypage/reviews/icons/review-grey-300.svg
  src/app/reviews/components/ReviewItem.tsx
  src/app/reviews/components/ReviewStatistics.tsx
  src/components/feedback/FeedbackScreen.tsx
  src/data/faq/index.tsx
Labels: 🎨 design

#491 fix: 내 후기에서 취소된 예약을 보여주던 이슈 해결
  src/app/mypage/reviews/components/WritableReviews.tsx
  src/app/mypage/reviews/components/WrittenReviews.tsx
Labels: 🐛 fix

#502 fix: 리뷰 전체보기 모바일에서 무한스크롤 안되는 이슈 및 UI 개선
  src/app/(home)/@bot/components/PromotionReviews.tsx
  src/app/mypage/reviews/[reviewId]/components/ReviewItem.tsx
  src/app/mypage/reviews/[reviewId]/components/ReviewListWithMyReview.tsx
  src/app/reviews/components/ReviewItem.tsx
  src/app/reviews/components/ReviewList.tsx
  src/hooks/useInfiniteScroll.tsx
Labels: 🎨 design, 🐛 fix

#504 design: UI 피드백 반영 (NotificationBubble, CouponSection, 핸디지원금정보)
  src/app/event/[eventId]/components/event-form/components/BottomBar.tsx
  src/app/event/[eventId]/dailyevent/[dailyEventId]/route/[shuttleRouteId]/payment/components/Content.tsx
  src/app/event/[eventId]/dailyevent/[dailyEventId]/route/[shuttleRouteId]/payment/components/sections/CouponSection.tsx
  src/app/event/[eventId]/dailyevent/[dailyEventId]/route/[shuttleRouteId]/payment/components/sections/PriceSection.tsx
  src/app/mypage/shuttle/reservation/[reservationId]/components/Content.tsx
  src/app/mypage/shuttle/reservation/[reservationId]/components/sections/price-section/PriceSection.tsx
  src/app/mypage/shuttle/reservation/[reservationId]/components/sections/price-section/components/RegularPriceContent.tsx
Labels: 🎨 design

#497 feat: V2 핸디팟 임시 처리
  src/app/event/[eventId]/components/steps/demand-steps/DemandHubsStep.tsx
  src/app/event/[eventId]/dailyevent/[dailyEventId]/route/[shuttleRouteId]/payment/components/Content.tsx
  src/app/help/handybus-guide/images/handyparty-guide-step-1.png
  src/app/help/handybus-guide/images/handyparty-guide-step-2.png
  src/app/help/handybus-guide/images/handyparty-guide-step-3.png
  src/app/help/handybus-guide/images/handyparty-guide-step-4.png
  src/app/help/handybus-guide/images/handyparty-guide-step-5.png
  src/app/help/handybus-guide/images/handyparty-guide-step-6.png
  src/app/help/handybus-guide/images/handyparty-guide-step-7.png
  src/app/help/handybus-guide/layout.tsx
  src/app/help/handybus-guide/page.tsx
Labels: ✨ feat

#506 feat: 수요조사 정류장 태깅 적용
  src/app/event/[eventId]/components/steps/demand-steps/DemandHubsStep.tsx
  src/app/help/about/components/AboutService.tsx
  src/app/mypage/reviews/components/reservation-card/hooks/useEventText.ts
  src/app/mypage/shuttle/components/reservations/reservation-card/hooks/useEventText.ts
Labels: ✨ feat

#507 fix: 행사 전체보기 페이지에서 행사 조회 오류 수정
  public/icons/event-empty.svg
  src/app/event/components/Empty.tsx
  src/app/event/components/Loading.tsx
  src/app/event/page.tsx
Labels: 🐛 fix

#511 fix: 행사 전체보기에서 판매대기 행사들 필터링
  src/app/event/page.tsx
Labels: 🐛 fix

#514 feat: 데드존 의견 남기기 버튼을 내부 의견 남기기 화면으로 통일
  src/app/help/faq/page.tsx
  src/components/dead-zone/DeadZonePopup.tsx
  src/components/feedback/FeedbackScreen.tsx
Labels: ✨ feat

#516 feat: 도움말 업데이트
  .prettierignore
  src/data/faq/boarding-1.mdx
  src/data/faq/boarding-2-what-bus-is-used-for-service.mdx
  src/data/faq/boarding-2.mdx
  src/data/faq/boarding-3.mdx
  src/data/faq/boarding-4.mdx
  src/data/faq/boarding-5.mdx
  src/data/faq/boarding-6-use-one-way-from-round-trip.mdx
  src/data/faq/boarding-6.mdx
  src/data/faq/etc-1.mdx
  src/data/faq/index.tsx
  src/data/faq/reservation-1-what-is-demand.mdx
  src/data/faq/reservation-1.mdx
  src/data/faq/reservation-10.mdx
  src/data/faq/reservation-11.mdx
  src/data/faq/reservation-2-when-can-i-book.mdx
  src/data/faq/reservation-2.mdx
  src/data/faq/reservation-3-how-many-people-needed-for-survey.mdx
  src/data/faq/reservation-3.mdx
  src/data/faq/reservation-4-no-desired-stop-in-survey.mdx
  src/data/faq/reservation-4.mdx
  src/data/faq/reservation-5-when-is-shuttle-confirmed.mdx
  src/data/faq/reservation-5.mdx
  src/data/faq/reservation-6-sold-out-additional-shuttle.mdx
  src/data/faq/reservation-6.mdx
  src/data/faq/reservation-7.mdx
  src/data/faq/reservation-8.mdx
  src/data/faq/reservation-9-cancel-reservation.mdx
  src/data/faq/reservation-9.mdx
Labels: ✨ feat

#518 feat: 점검중 표시 반영
  src/app/layout.tsx
  src/components/service-maintenance-screen/ServiceMaintenanceScreen.tsx
Labels: ✨ feat

#520 feat: 리뷰 피드백 텍스트 api 반영
  src/app/(home)/@bot/components/PromotionReviews.tsx
  src/app/mypage/reviews/[reviewId]/components/ReviewItem.tsx
  src/app/reviews/components/ReviewItem.tsx
  src/components/review/ReviewProperty.tsx
  src/types/review.type.ts
Labels: ✨ feat

#521 design: 핸디버스 가이드 문구 수정
  src/app/help/handybus-guide/page.tsx
Labels: 🎨 design

#522 fix: 첫 진입 시 캐러셀 숫자 미표시 버그 수정
  src/app/(home)/@event/components/RecommendedEventSwiperView.tsx
  src/app/(home)/@event/components/TrendEventsSwiperView.tsx
  src/app/(home)/@event/page.tsx
Labels: 🐛 fix

#523 feat: 유의사항 업데이트
  src/app/event/[eventId]/components/EventGuidelines.tsx
  src/app/mypage/shuttle/demand/[demandId]/components/sections/GuidelineSection.tsx
  src/app/mypage/shuttle/reservation/[reservationId]/components/sections/GuidelineSection.tsx
  src/components/guidelines/Guideline.tsx
  src/components/guidelines/contents/CancellationAndRefund.tsx
  src/components/guidelines/contents/Demand.tsx
  src/components/guidelines/contents/Inquiry.tsx
  src/components/guidelines/contents/Notice.tsx
Labels: ✨ feat

#530 design: 상품별 유의사항 변경
  src/components/guidelines/contents/Notice.tsx
Labels: 🎨 design

#531 release: V2
  src/app/(home)/@bot/components/AnnouncementPreview.tsx
  src/app/announcements/components/AnnouncementList.tsx
  src/app/mypage/reviews/components/reservation-card/hooks/useEventText.ts
  src/app/mypage/shuttle/components/reservations/reservation-card/hooks/useEventText.ts
  src/components/guidelines/contents/Notice.tsx
Labels: 🔖 release, 🎨 design, 🐛 fix

#528 fix: 리뷰 조회 시에 정렬 파라미터 적용
  src/app/(home)/@bot/components/PromotionReviews.tsx
  src/app/mypage/reviews/[reviewId]/components/ReviewListWithMyReview.tsx
  src/app/reviews/components/ReviewList.tsx
  src/services/review.service.ts
Labels: 🐛 fix

#533 design: n월의 추천 행사에서 이달의 추천 행사로 명칭 변경
  src/app/(home)/@event/components/RecommendedEventCard.tsx
Labels: 🎨 design

#535 design: 일자별 수요조사 모집 중 버튼 ui및 텍스트 변경
  src/app/event/[eventId]/components/steps/common-steps/CommonDateStep.tsx
Labels: 🎨 design

#536 release: V2
  src/app/(home)/@bot/components/PromotionReviews.tsx
  src/app/(home)/@event/components/RecommendedEventCard.tsx
  src/app/event/[eventId]/components/steps/common-steps/CommonDateStep.tsx
  src/app/mypage/reviews/[reviewId]/components/ReviewListWithMyReview.tsx
  src/app/mypage/shuttle/reservation/[reservationId]/components/Content.tsx
  src/app/mypage/shuttle/reservation/[reservationId]/components/sections/shuttle-progress-section/ShuttleProgressSection.tsx
  src/app/reviews/components/ReviewList.tsx
  src/services/review.service.ts
Labels: 🔖 release

#537 fix: 배포환경에서 가끔 카드의 숫자가 사라지는 이슈 해결
  src/components/card/Card.tsx
Labels: 🐛 fix

#543 fix: 빈자리 알림 취소
  src/app/mypage/alert-requests/components/AlertRequestCard.tsx
Labels: 🐛 fix

#544 release: V2
  src/app/mypage/alert-requests/components/AlertRequestCard.tsx
Labels: 🔖 release

#545 hotfix: 예약 정류장 바텀시트에서 수요조사가 열렸을 때에만 요청하기 버튼 표시
  src/app/event/[eventId]/components/steps/reservation-steps/ReservationHubsStep.tsx
Labels: 🐛 fix, 🔥 hotfix

#546 release: V2
  src/app/event/[eventId]/components/steps/reservation-steps/ReservationHubsStep.tsx
Labels: 🔖 release

#547 fix: 핸디팟 정류장을 수요조사 단계에서 최근에 본 정류장에 뜨지 않도록 처리
  src/app/event/[eventId]/components/steps/demand-steps/DemandHubsStep.tsx
  src/app/event/[eventId]/components/steps/reservation-steps/ReservationHubsStep.tsx
Labels: 🐛 fix

#548 release: V2
  src/app/event/[eventId]/components/steps/demand-steps/DemandHubsStep.tsx
  src/app/event/[eventId]/components/steps/reservation-steps/ReservationHubsStep.tsx
Labels: 🔖 release

#549 fix: 버튼 비활성화 디자인 반영 및 텍스트 깨짐 현상 처리
  src/app/event/[eventId]/components/steps/extra-steps/ExtraHubsInRouteStep.tsx
  src/app/event/[eventId]/components/steps/reservation-steps/ReservationHubsStep.tsx
  src/components/buttons/button/Button.tsx
Labels: 🐛 fix

#540 feat: 빈자리알림 상세 내역 페이지
  src/app/mypage/alert-requests/[alertRequestId]/components/Content.tsx
  src/app/mypage/alert-requests/[alertRequestId]/components/EventCard.tsx
  src/app/mypage/alert-requests/[alertRequestId]/components/WrapperWithDivider.tsx
  src/app/mypage/alert-requests/[alertRequestId]/components/section/GuidelineSection.tsx
  src/app/mypage/alert-requests/[alertRequestId]/components/section/ShuttleRouteInfoSection.tsx
  src/app/mypage/alert-requests/[alertRequestId]/components/section/shuttle-progress-section/ShuttleProgressSection.tsx
  src/app/mypage/alert-requests/[alertRequestId]/components/section/shuttle-progress-section/hooks/useText.tsx
  src/app/mypage/alert-requests/[alertRequestId]/page.tsx
  src/app/mypage/alert-requests/components/AlertRequestCard.tsx
Labels: ✨ feat

#554 feat: 약관 업데이트 및 관련 환불 로직 대응
  src/app/mypage/shuttle/reservation/[reservationId]/components/sections/refund-section/RefundSection.tsx
  src/components/guidelines/contents/Notice.tsx
  src/data/policy/service.mdx
  src/mdx-components.tsx
  src/utils/reservation.util.ts
Labels: ✨ feat

#555 release: V2
  src/app/event/[eventId]/dailyevent/[dailyEventId]/route/[shuttleRouteId]/payment/components/Content.tsx
  src/app/mypage/alert-requests/[alertRequestId]/components/Content.tsx
  src/app/mypage/alert-requests/[alertRequestId]/components/EventCard.tsx
  src/app/mypage/alert-requests/[alertRequestId]/components/WrapperWithDivider.tsx
  src/app/mypage/alert-requests/[alertRequestId]/components/section/GuidelineSection.tsx
  src/app/mypage/alert-requests/[alertRequestId]/components/section/ShuttleRouteInfoSection.tsx
  src/app/mypage/alert-requests/[alertRequestId]/components/section/shuttle-progress-section/ShuttleProgressSection.tsx
  src/app/mypage/alert-requests/[alertRequestId]/components/section/shuttle-progress-section/hooks/useText.tsx
  src/app/mypage/alert-requests/[alertRequestId]/page.tsx
  src/app/mypage/alert-requests/components/AlertRequestCard.tsx
  src/app/mypage/shuttle/reservation/[reservationId]/components/sections/refund-section/RefundSection.tsx
  src/components/guidelines/contents/Notice.tsx
  src/data/policy/service.mdx
  src/mdx-components.tsx
  src/utils/reservation.util.ts
Labels: 🔖 release

#558 feat: 핸디팟 노선일 경우 노선도에서 시간 미표시
  src/app/event/[eventId]/components/images/event-overview.png
  src/app/event/[eventId]/components/shuttle-route-detail-view/ShuttleRouteDetailView.tsx
  src/app/event/[eventId]/components/shuttle-route-detail-view/components/Hub.tsx
  src/app/event/[eventId]/components/shuttle-route-detail-view/components/Hubs.tsx
Labels: ✨ feat

#560 feat: 행사의 수요조사 수를 보여주는 단위 수정
  src/app/event/[eventId]/components/steps/common-steps/CommonDateStep.tsx
  src/app/event/[eventId]/components/steps/demand-steps/DemandHubsStep.tsx
Labels: ✨ feat

#557 feat: GA4 수요조사, 자주묻는 질문 유저 트래킹 추가
  docs/DEMAND_TRACKING.md
  docs/FAQ_TRACKING.md
  src/app/event/[eventId]/components/event-form/EventForm.tsx
  src/app/event/[eventId]/components/steps/StepComponent.tsx
  src/app/event/[eventId]/components/steps/demand-steps/DemandHubInfoStep.tsx
  src/app/help/faq/components/FAQList.tsx
  src/app/layout.tsx
  src/components/accordion/Accordion.tsx
  src/hooks/analytics/useDemandTracking.tsx
  src/hooks/analytics/useFAQTracking.tsx
  src/types/global/global-gtag.d.ts
  src/utils/analytics/demandAnalytics.util.ts
  src/utils/analytics/faqAnalytics.util.ts
Labels: ✨ feat

#559 feat: 완전 편도 노선 대응
  src/app/event/[eventId]/components/shuttle-route-detail-view/ShuttleRouteDetailView.tsx
  src/app/event/[eventId]/components/steps/components/SimpleRouteInfo.tsx
  src/app/event/[eventId]/components/steps/demand-steps/DemandHubsStep.tsx
  src/app/event/[eventId]/components/steps/extra-steps/ExtraDuplicateHubStep.tsx
  src/app/event/[eventId]/components/steps/reservation-steps/ReservationTripTypeStep.tsx
  src/app/event/[eventId]/dailyevent/[dailyEventId]/route/[shuttleRouteId]/payment/components/Content.tsx
  src/app/event/[eventId]/dailyevent/[dailyEventId]/route/[shuttleRouteId]/payment/components/sections/ShuttleRouteInfoSection.tsx
  src/app/event/[eventId]/dailyevent/[dailyEventId]/route/[shuttleRouteId]/payment/page.tsx
  src/app/event/[eventId]/dailyevent/[dailyEventId]/route/[shuttleRouteId]/payment/payment.const.ts
  src/app/event/[eventId]/store/dailyEventIdsWithHubsAtom.ts
  src/app/mypage/shuttle/reservation/[reservationId]/components/Content.tsx
  src/app/mypage/shuttle/reservation/[reservationId]/components/sections/shuttle-info-section/ShuttleInfoSection.tsx
  src/app/mypage/shuttle/reservation/[reservationId]/components/sections/shuttle-info-section/components/HubItem.tsx
  src/app/mypage/shuttle/reservation/[reservationId]/components/sections/shuttle-info-section/components/TripCard.tsx
  src/components/tab/Tabs.tsx
  src/types/shuttleRoute.type.ts
  src/utils/event.util.ts
  src/utils/taxiRoute.util.ts
Labels: ✨ feat

#562 fix: 수요조사 GA 플로우 수정
  src/app/event/[eventId]/components/event-form/EventForm.tsx
  src/app/event/[eventId]/components/steps/StepComponent.tsx
  src/app/event/[eventId]/components/steps/demand-steps/DemandHubInfoStep.tsx
  src/hooks/analytics/useDemandTracking.tsx
  src/utils/analytics/demandAnalytics.util.ts
Labels: 🐛 fix

#563 fix: 핸디팟 정류장일때 지도 클릭시 404 페이지 이슈
  src/app/event/[eventId]/components/shuttle-route-detail-view/components/KakaoMap.tsx
Labels: 🐛 fix
