Repository HandyBus/handybus-web-latest, pull requests merged in 2025-07, with the labels that each got.

#565 feat: 핸디팟 노선 오픈채팅방 및 핸디 로직 제거 반영
  src/app/event/[eventId]/components/shuttle-route-detail-view/components/Hub.tsx
  src/app/event/[eventId]/components/steps/components/SimpleRouteInfo.tsx
  src/app/event/[eventId]/dailyevent/[dailyEventId]/route/[shuttleRouteId]/payment/components/sections/ShuttleRouteInfoSection.tsx
  src/app/mypage/shuttle/components/reservations/reservation-card/ReservationCard.tsx
  src/app/mypage/shuttle/components/reservations/reservation-card/components/ChatButton.tsx
  src/app/mypage/shuttle/components/reservations/reservation-card/hooks/useTextAndStyle.ts
  src/app/mypage/shuttle/hooks/useReservationProgress.ts
  src/app/mypage/shuttle/reservation/[reservationId]/components/sections/shuttle-info-section/components/HubItem.tsx
  src/app/mypage/shuttle/reservation/[reservationId]/components/sections/shuttle-progress-section/ShuttleProgressSection.tsx
  src/app/mypage/shuttle/reservation/[reservationId]/components/sections/shuttle-progress-section/hooks/useText.tsx
  src/app/mypage/shuttle/reservation/[reservationId]/components/sections/shuttle-progress-section/icons/icon-check.svg
Labels: ✨ feat

#566 fix: 노선 방향에 따라 hub id 빈 값으로 처리하여 예약 생성
  src/app/event/[eventId]/dailyevent/[dailyEventId]/route/[shuttleRouteId]/payment/components/Content.tsx
Labels: 🐛 fix

#568 feat: 핸디팟 노선 예약 및 주소 입력
  src/app/event/[eventId]/components/handy-party/HandyPartyModal.tsx
  src/app/event/[eventId]/components/handy-party/components/Header.tsx
  src/app/event/[eventId]/components/handy-party/components/SimpleRouteInfo.tsx
  src/app/event/[eventId]/components/handy-party/components/steps/AddressStep.tsx
  src/app/event/[eventId]/components/handy-party/components/steps/MapStep.tsx
  src/app/event/[eventId]/components/handy-party/components/steps/ReservationInfoStep.tsx
  src/app/event/[eventId]/components/handy-party/components/steps/TripTypeStep.tsx
  src/app/event/[eventId]/components/handy-party/icons/add.svg
  src/app/event/[eventId]/components/handy-party/icons/arrow-left.svg
  src/app/event/[eventId]/components/handy-party/icons/dot-primary.svg
  src/app/event/[eventId]/components/handy-party/icons/pin-primary.svg
  src/app/event/[eventId]/components/handy-party/icons/search.svg
  src/app/event/[eventId]/components/handy-party/icons/subtract.svg
  src/app/event/[eventId]/components/images/event-overview.png
  src/app/event/[eventId]/components/shuttle-route-detail-view/ShuttleRouteDetailView.tsx
  src/app/event/[eventId]/components/shuttle-route-detail-view/components/Hubs.tsx
  src/app/event/[eventId]/components/steps/StepComponent.tsx
  src/app/event/[eventId]/components/steps/common-steps/CommonSidoStep.tsx
  src/app/event/[eventId]/components/steps/extra-steps/ExtraOpenSidoStep.tsx
  src/app/event/[eventId]/components/steps/extra-steps/ExtraSelectProductStep.tsx
  src/app/event/[eventId]/components/steps/reservation-steps/ReservationHubsStep.tsx
  src/app/event/[eventId]/dailyevent/[dailyEventId]/route/[shuttleRouteId]/payment/components/Content.tsx
  src/app/event/[eventId]/dailyevent/[dailyEventId]/route/[shuttleRouteId]/payment/components/sections/ShuttleRouteInfoSection.tsx
  src/app/event/[eventId]/dailyevent/[dailyEventId]/route/[shuttleRouteId]/payment/page.tsx
  src/app/event/[eventId]/dailyevent/[dailyEventId]/route/[shuttleRouteId]/payment/payment.const.ts
  src/app/event/[eventId]/form.const.tsx
  src/app/event/[eventId]/icons/handy-party.svg
  src/app/event/[eventId]/icons/shuttle-bus.svg
  src/app/mypage/reviews/components/reservation-card/ReservationCardForReview.tsx
  src/app/mypage/reviews/components/reservation-card/hooks/useEventText.ts
  src/app/mypage/reviews/components/reservation-card/hooks/useTextAndStyleForReview.ts
  src/app/mypage/shuttle/components/reservations/reservation-card/ReservationCard.tsx
  src/app/mypage/shuttle/components/reservations/reservation-card/components/ChatButton.tsx
  src/app/mypage/shuttle/components/reservations/reservation-card/hooks/useEventText.ts
  src/app/mypage/shuttle/components/reservations/reservation-card/hooks/useTextAndStyle.ts
  src/app/mypage/shuttle/hooks/useReservationProgress.ts
  src/app/mypage/shuttle/reservation/[reservationId]/components/Content.tsx
  src/app/mypage/shuttle/reservation/[reservationId]/components/sections/shuttle-info-section/ShuttleInfoSection.tsx
  src/app/mypage/shuttle/reservation/[reservationId]/components/sections/shuttle-info-section/components/HubItem.tsx
  src/app/mypage/shuttle/reservation/[reservationId]/components/sections/shuttle-info-section/components/TripCard.tsx
  src/app/mypage/shuttle/reservation/[reservationId]/components/sections/shuttle-progress-section/ShuttleProgressSection.tsx
  src/app/mypage/shuttle/reservation/[reservationId]/components/sections/shuttle-progress-section/hooks/useText.tsx
  src/components/kakao-map/KakaoMap.tsx
  src/components/kakao-map/KakaoMap.type.ts
  src/components/kakao-map/KakaoMapScript.tsx
  src/constants/common.ts
  src/constants/handyPartyArea.const.ts
  src/types/event.type.ts
  src/types/payment.type.ts
  src/types/reservation.type.ts
  src/utils/handyParty.util.ts
  src/utils/taxiRoute.util.ts
Labels: ✨ feat

#569 release: V2
  src/app/event/[eventId]/components/handy-party/HandyPartyModal.tsx
  src/app/event/[eventId]/components/handy-party/components/Header.tsx
  src/app/event/[eventId]/components/handy-party/components/SimpleRouteInfo.tsx
  src/app/event/[eventId]/components/handy-party/components/steps/AddressStep.tsx
  src/app/event/[eventId]/components/handy-party/components/steps/MapStep.tsx
  src/app/event/[eventId]/components/handy-party/components/steps/ReservationInfoStep.tsx
  src/app/event/[eventId]/components/handy-party/components/steps/TripTypeStep.tsx
  src/app/event/[eventId]/components/handy-party/icons/add.svg
  src/app/event/[eventId]/components/handy-party/icons/arrow-left.svg
  src/app/event/[eventId]/components/handy-party/icons/dot-primary.svg
  src/app/event/[eventId]/components/handy-party/icons/pin-primary.svg
  src/app/event/[eventId]/components/handy-party/icons/search.svg
  src/app/event/[eventId]/components/handy-party/icons/subtract.svg
  src/app/event/[eventId]/components/images/event-overview.png
  src/app/event/[eventId]/components/shuttle-route-detail-view/ShuttleRouteDetailView.tsx
  src/app/event/[eventId]/components/shuttle-route-detail-view/components/Hubs.tsx
  src/app/event/[eventId]/components/steps/StepComponent.tsx
  src/app/event/[eventId]/components/steps/common-steps/CommonSidoStep.tsx
  src/app/event/[eventId]/components/steps/extra-steps/ExtraOpenSidoStep.tsx
  src/app/event/[eventId]/components/steps/extra-steps/ExtraSelectProductStep.tsx
  src/app/event/[eventId]/components/steps/reservation-steps/ReservationHubsStep.tsx
  src/app/event/[eventId]/dailyevent/[dailyEventId]/route/[shuttleRouteId]/payment/components/Content.tsx
  src/app/event/[eventId]/dailyevent/[dailyEventId]/route/[shuttleRouteId]/payment/components/sections/ShuttleRouteInfoSection.tsx
  src/app/event/[eventId]/dailyevent/[dailyEventId]/route/[shuttleRouteId]/payment/page.tsx
  src/app/event/[eventId]/dailyevent/[dailyEventId]/route/[shuttleRouteId]/payment/payment.const.ts
  src/app/event/[eventId]/form.const.tsx
  src/app/event/[eventId]/icons/handy-party.svg
  src/app/event/[eventId]/icons/shuttle-bus.svg
  src/app/mypage/reviews/components/reservation-card/ReservationCardForReview.tsx
  src/app/mypage/reviews/components/reservation-card/hooks/useEventText.ts
  src/app/mypage/reviews/components/reservation-card/hooks/useTextAndStyleForReview.ts
  src/app/mypage/shuttle/components/reservations/reservation-card/ReservationCard.tsx
  src/app/mypage/shuttle/components/reservations/reservation-card/components/ChatButton.tsx
  src/app/mypage/shuttle/components/reservations/reservation-card/hooks/useEventText.ts
  src/app/mypage/shuttle/components/reservations/reservation-card/hooks/useTextAndStyle.ts
  src/app/mypage/shuttle/hooks/useReservationProgress.ts
  src/app/mypage/shuttle/reservation/[reservationId]/components/Content.tsx
  src/app/mypage/shuttle/reservation/[reservationId]/components/sections/shuttle-info-section/ShuttleInfoSection.tsx
  src/app/mypage/shuttle/reservation/[reservationId]/components/sections/shuttle-info-section/components/HubItem.tsx
  src/app/mypage/shuttle/reservation/[reservationId]/components/sections/shuttle-info-section/components/TripCard.tsx
  src/app/mypage/shuttle/reservation/[reservationId]/components/sections/shuttle-progress-section/ShuttleProgressSection.tsx
  src/app/mypage/shuttle/reservation/[reservationId]/components/sections/shuttle-progress-section/hooks/useText.tsx
  src/components/kakao-map/KakaoMap.tsx
  src/components/kakao-map/KakaoMap.type.ts
  src/components/kakao-map/KakaoMapScript.tsx
  src/constants/common.ts
  src/constants/handyPartyArea.const.ts
  src/types/event.type.ts
  src/types/payment.type.ts
  src/types/reservation.type.ts
  src/utils/handyParty.util.ts
  src/utils/taxiRoute.util.ts
Labels: 🔖 release

#571 release: V2
  src/components/guidelines/contents/Notice.tsx
Labels: 🔖 release

#572 feat: 가이드 업데이트
  src/app/help/about/images/service-overview-1.png
  src/app/help/about/images/service-overview-2.png
  src/app/help/about/page.tsx
  src/app/help/handybus-guide/images/handyparty-guide-step-3.png
  src/app/help/handybus-guide/images/handyparty-guide-step-5.png
  src/app/help/handybus-guide/images/handyparty-guide-step-6.png
  src/app/help/handybus-guide/images/handyparty-guide-step-7.png
  src/app/help/handybus-guide/page.tsx
Labels: ✨ feat

#573 feat: 핸디팟 동 지역 제한 및 예약 가능 지역 문구 추가
  src/app/event/[eventId]/components/EventInfo.tsx
  src/app/event/[eventId]/components/event-form/EventForm.tsx
  src/app/event/[eventId]/components/handy-party/HandyPartyModal.tsx
  src/app/event/[eventId]/components/handy-party/components/steps/AddressStep.tsx
  src/app/event/[eventId]/components/handy-party/components/steps/MapStep.tsx
  src/app/event/[eventId]/components/handy-party/components/steps/TripTypeStep.tsx
  src/app/event/[eventId]/components/shuttle-route-detail-view/components/KakaoMap.tsx
  src/app/event/[eventId]/components/steps/components/SimpleRouteInfo.tsx
  src/app/event/[eventId]/components/steps/demand-steps/DemandHubsStep.tsx
  src/app/mypage/shuttle/reservation/[reservationId]/components/Content.tsx
  src/constants/handyPartyArea.const.ts
  src/utils/handyParty.util.ts
  src/utils/taxiRoute.util.ts
Labels: ✨ feat

#575 feat: 전체 행사 필터 추가 및 스포츠 타입 반영
  src/app/(home)/@event/components/RecommendedEventCard.tsx
  src/app/event/components/FilterBar.tsx
  src/app/event/page.tsx
  src/components/chips/Chip.tsx
  src/constants/status.ts
  src/types/event.type.ts
Labels: ✨ feat

#576 design: 핸디팟 가이드 문구 디자인 일부 수정
  src/app/event/[eventId]/components/handy-party/components/steps/AddressStep.tsx
  src/app/event/[eventId]/components/handy-party/components/steps/MapStep.tsx
  src/app/event/[eventId]/components/shuttle-route-detail-view/ShuttleRouteDetailView.tsx
Labels: 🎨 design

#578 release: V2
  src/app/(home)/@event/components/RecommendedEventCard.tsx
  src/app/event/[eventId]/components/EventInfo.tsx
  src/app/event/[eventId]/components/event-form/EventForm.tsx
  src/app/event/[eventId]/components/handy-party/HandyPartyModal.tsx
  src/app/event/[eventId]/components/handy-party/components/steps/AddressStep.tsx
  src/app/event/[eventId]/components/handy-party/components/steps/MapStep.tsx
  src/app/event/[eventId]/components/handy-party/components/steps/TripTypeStep.tsx
  src/app/event/[eventId]/components/shuttle-route-detail-view/ShuttleRouteDetailView.tsx
  src/app/event/[eventId]/components/shuttle-route-detail-view/components/KakaoMap.tsx
  src/app/event/[eventId]/components/steps/components/SimpleRouteInfo.tsx
  src/app/event/[eventId]/components/steps/demand-steps/DemandHubsStep.tsx
  src/app/event/components/FilterBar.tsx
  src/app/event/page.tsx
  src/app/help/about/images/service-overview-1.png
  src/app/help/about/images/service-overview-2.png
  src/app/help/about/page.tsx
  src/app/help/handybus-guide/images/handyparty-guide-step-3.png
  src/app/help/handybus-guide/images/handyparty-guide-step-5.png
  src/app/help/handybus-guide/images/handyparty-guide-step-6.png
  src/app/help/handybus-guide/images/handyparty-guide-step-7.png
  src/app/help/handybus-guide/page.tsx
  src/app/mypage/shuttle/components/reservations/reservation-card/hooks/useEventText.ts
  src/app/mypage/shuttle/reservation/[reservationId]/components/Content.tsx
  src/app/mypage/shuttle/reservation/[reservationId]/components/sections/shuttle-info-section/ShuttleInfoSection.tsx
  src/components/chips/Chip.tsx
  src/constants/handyPartyArea.const.ts
  src/constants/status.ts
  src/types/event.type.ts
  src/utils/handyParty.util.ts
  src/utils/taxiRoute.util.ts
Labels: 🔖 release

#579 fix: 용인 지역 주소 검색 제한 상수 수정
  src/app/event/page.tsx
  src/constants/handyPartyArea.const.ts
Labels: 🐛 fix

#580 release: V2
  src/app/event/page.tsx
  src/constants/handyPartyArea.const.ts
Labels: 🔖 release

#582 feat: 티원 경품 추첨 모달
  src/app/(home)/@modal/components/T1Modal.tsx
  src/app/(home)/@modal/images/t1_0711.png
  src/app/(home)/@modal/page.tsx
  src/app/(home)/layout.tsx
  src/app/event/[eventId]/components/EventModal.tsx
  src/app/event/[eventId]/page.tsx
  src/utils/localStorage.ts
Labels: ✨ feat

#583 release: V2
  src/app/(home)/@modal/components/T1Modal.tsx
  src/app/(home)/@modal/images/t1_0711.png
  src/app/(home)/@modal/page.tsx
  src/app/(home)/layout.tsx
  src/app/event/[eventId]/components/EventModal.tsx
  src/app/event/[eventId]/components/EventOverview.tsx
  src/app/event/[eventId]/components/images/event-overview.png
  src/app/event/[eventId]/page.tsx
  src/utils/localStorage.ts
Labels: 🔖 release

#591 feat: 특정 행사에만 사용 가능한 쿠폰 반영
  src/app/event/[eventId]/dailyevent/[dailyEventId]/route/[shuttleRouteId]/payment/components/Content.tsx
  src/app/event/[eventId]/dailyevent/[dailyEventId]/route/[shuttleRouteId]/payment/components/sections/CouponSection.tsx
  src/types/coupon.type.ts
Labels: ✨ feat

#593 feat: 남은 좌석 수 숨김 처리
  src/app/event/[eventId]/components/steps/extra-steps/ExtraDuplicateHubStep.tsx
  src/app/event/[eventId]/components/steps/reservation-steps/ReservationHubsStep.tsx
  src/app/event/[eventId]/components/steps/reservation-steps/ReservationTripTypeStep.tsx
Labels: ✨ feat

#590 feat: GA4 공유하기
  docs/SHARE_TRACKING.md
  src/app/event/[eventId]/components/event-form/components/BottomBar.tsx
  src/app/event/[eventId]/components/event-form/components/ShareBottomSheet.tsx
  src/hooks/analytics/useDemandTracking.ts
  src/hooks/analytics/useFAQTracking.ts
  src/hooks/analytics/useScrollDepth.ts
  src/hooks/analytics/useShareTracking.ts
  src/hooks/useShare.tsx
  src/services/reservation.service.ts
  src/utils/analytics/shareAnalytics.util.ts
Labels: ✨ feat

#594 feat: 티원 행사 전용 상세 이미지 추가
  src/app/event/[eventId]/components/EventOverview.tsx
  src/app/event/[eventId]/components/images/t1_faq.png
Labels: ✨ feat

#596 design: 특정 행사에서 사용 가능한 쿠폰 디자인 반영
  src/app/event/[eventId]/dailyevent/[dailyEventId]/route/[shuttleRouteId]/payment/components/sections/CouponSection.tsx
  src/app/event/[eventId]/dailyevent/[dailyEventId]/route/[shuttleRouteId]/payment/icons/radio-disabled.svg
  src/components/coupon/Coupon.tsx
  src/services/coupon.service.ts
  src/services/event.service.ts
Labels: 🎨 design

#598 feat: 티원 모달을 하루 안보기 공통 모달로 변환
  src/app/(home)/@modal/components/OneDayModal.tsx
  src/app/(home)/@modal/components/T1Modal.tsx
  src/app/(home)/@modal/images/t1_0711.png
  src/app/(home)/@modal/page.tsx
  src/app/event/[eventId]/components/EventModal.tsx
  src/app/event/[eventId]/components/EventOverview.tsx
  src/utils/localStorage.ts
Labels: ✨ feat

#599 release: V2
  src/app/(home)/@modal/components/OneDayModal.tsx
  src/app/(home)/@modal/components/T1Modal.tsx
  src/app/(home)/@modal/images/t1_0711.png
  src/app/(home)/@modal/page.tsx
  src/app/event/[eventId]/components/EventModal.tsx
  src/app/event/[eventId]/components/EventOverview.tsx
  src/utils/localStorage.ts
Labels: 🔖 release

#600 feat: 환불 불가 기간에도 예약 취소 가능하도록 개선
  src/app/mypage/shuttle/reservation/[reservationId]/components/sections/refund-section/RefundSection.tsx
  src/app/mypage/shuttle/reservation/[reservationId]/components/sections/refund-section/components/CancelBottomSheet.tsx
  src/components/guidelines/contents/Notice.tsx
  src/data/faq/index.tsx
  src/data/faq/reservation-9.mdx
  src/services/payment.service.ts
  src/services/reservation.service.ts
  src/types/reservation.type.ts
  src/types/shuttleBus.type.ts
  src/utils/reservation.util.ts
Labels: ✨ feat

#601 feat: 공지사항 배너
  src/app/(home)/@top/components/AnnouncementBanner.tsx
  src/app/(home)/@top/page.tsx
Labels: ✨ feat

#602 release: V2
  src/app/(home)/@top/components/AnnouncementBanner.tsx
  src/app/(home)/@top/page.tsx
  src/app/mypage/shuttle/reservation/[reservationId]/components/sections/refund-section/RefundSection.tsx
  src/app/mypage/shuttle/reservation/[reservationId]/components/sections/refund-section/components/CancelBottomSheet.tsx
  src/components/guidelines/contents/Notice.tsx
  src/data/faq/index.tsx
  src/data/faq/reservation-9.mdx
  src/services/payment.service.ts
  src/services/reservation.service.ts
  src/types/reservation.type.ts
  src/types/shuttleBus.type.ts
  src/utils/reservation.util.ts
Labels: 🔖 release

#604 release: V2
  src/app/event/[eventId]/components/event-form/components/BottomBar.tsx
  src/utils/event.util.ts
Labels: 🔖 release

#606 chore: 개인정보약관 업데이트
  src/data/policy/privacy.mdx
Labels: 🧹 chore

#607 chore: 상단 중요 공지 비활성화
  src/app/(home)/@top/page.tsx
Labels: 🧹 chore

#608 release: V2
  src/app/(home)/@event/components/RecommendedEventSwiperView.tsx
  src/app/(home)/@top/page.tsx
  src/data/policy/privacy.mdx
Labels: 🔖 release

#610 feat: 수요조사 리워드 쿠폰
  src/app/event/[eventId]/components/EventInfo.tsx
  src/app/event/[eventId]/components/demand-complete-screen/DemandCompleteScreen.tsx
  src/app/event/[eventId]/components/demand-complete-screen/SuccessScreen.tsx
  src/app/event/[eventId]/components/event-form/EventForm.tsx
  src/app/event/[eventId]/components/event-form/components/BottomBar.tsx
  src/app/event/[eventId]/components/event-form/components/ShareBottomSheet.tsx
  src/app/event/[eventId]/components/steps/StepComponent.tsx
  src/app/event/[eventId]/components/steps/demand-steps/DemandHubInfoStep.tsx
  src/app/event/[eventId]/components/steps/demand-steps/DemandHubsStep.tsx
  src/app/event/[eventId]/icons/demand-success.svg
  src/app/mypage/coupons/components/RegisterCoupon.tsx
  src/components/bottom-sheet/BottomSheet.tsx
  src/services/coupon.service.ts
Labels: ✨ feat

#611 feat: 실명제 도입
  src/app/(home)/@bot/components/PromotionReviews.tsx
  src/app/(home)/@greeting/page.tsx
  src/app/event/[eventId]/components/event-form/EventForm.tsx
  src/app/event/[eventId]/components/steps/StepComponent.tsx
  src/app/event/[eventId]/components/steps/extra-steps/ExtraRealNameInputStep.tsx
  src/app/event/[eventId]/components/steps/reservation-steps/ReservationInfoStep.tsx
  src/app/event/[eventId]/dailyevent/[dailyEventId]/route/[shuttleRouteId]/payment/components/sections/ClientInfoSection.tsx
  src/app/event/[eventId]/form.const.tsx
  src/app/event/[eventId]/form.type.ts
  src/app/mypage/components/Profile.tsx
  src/app/mypage/page.tsx
  src/app/mypage/profile/edit/components/EditForm.tsx
  src/app/mypage/reviews/[reviewId]/components/ReviewItem.tsx
  src/app/reviews/components/ReviewItem.tsx
  src/components/header/Header.tsx
  src/components/header/UserProfile.tsx
  src/components/onboarding-contents/ProfileInfoContent.tsx
  src/components/onboarding-contents/formValidation.const.ts
  src/components/onboarding-contents/onboarding.type.ts
  src/types/review.type.ts
  src/types/user.type.ts
  src/utils/generateProfileBackgroundColor.ts
Labels: ✨ feat

#612 release: V2
  src/app/(home)/@bot/components/PromotionReviews.tsx
  src/app/(home)/@greeting/page.tsx
  src/app/event/[eventId]/components/EventInfo.tsx
  src/app/event/[eventId]/components/demand-complete-screen/DemandCompleteScreen.tsx
  src/app/event/[eventId]/components/demand-complete-screen/SuccessScreen.tsx
  src/app/event/[eventId]/components/event-form/EventForm.tsx
  src/app/event/[eventId]/components/event-form/components/BottomBar.tsx
  src/app/event/[eventId]/components/event-form/components/ShareBottomSheet.tsx
  src/app/event/[eventId]/components/steps/StepComponent.tsx
  src/app/event/[eventId]/components/steps/demand-steps/DemandHubInfoStep.tsx
  src/app/event/[eventId]/components/steps/demand-steps/DemandHubsStep.tsx
  src/app/event/[eventId]/components/steps/extra-steps/ExtraRealNameInputStep.tsx
  src/app/event/[eventId]/components/steps/reservation-steps/ReservationHubsStep.tsx
  src/app/event/[eventId]/components/steps/reservation-steps/ReservationInfoStep.tsx
  src/app/event/[eventId]/dailyevent/[dailyEventId]/route/[shuttleRouteId]/payment/components/sections/ClientInfoSection.tsx
  src/app/event/[eventId]/form.const.tsx
  src/app/event/[eventId]/form.type.ts
  src/app/event/[eventId]/icons/demand-success.svg
  src/app/mypage/components/Profile.tsx
  src/app/mypage/coupons/components/RegisterCoupon.tsx
  src/app/mypage/page.tsx
  src/app/mypage/profile/edit/components/EditForm.tsx
  src/app/mypage/reviews/[reviewId]/components/ReviewItem.tsx
  src/app/reviews/components/ReviewItem.tsx
  src/components/bottom-sheet/BottomSheet.tsx
  src/components/header/Header.tsx
  src/components/header/UserProfile.tsx
  src/components/onboarding-contents/ProfileInfoContent.tsx
  src/components/onboarding-contents/formValidation.const.ts
  src/components/onboarding-contents/onboarding.type.ts
  src/services/coupon.service.ts
  src/types/review.type.ts
  src/types/user.type.ts
  src/utils/generateProfileBackgroundColor.ts
Labels: 🔖 release
