Repository HandyBus/handybus-web-latest, pull requests merged in 2025-09, with the labels that each got.

#680 release: V2
  src/app/(home)/@bot/page.tsx
  src/app/mypage/reviews/[reviewId]/components/ReviewListWithMyReview.tsx
  src/app/reviews/layout.tsx
  src/app/reviews/page.tsx
  src/app/sitemap.ts
Labels: 🔖 release

#683 feat: 세븐틴 임시 노선별 오픈채팅방링크 연결
  src/app/event/[eventId]/dailyevent/[dailyEventId]/route/[shuttleRouteId]/payment/request/[reservationId]/page.tsx
  src/app/mypage/boarding-pass/hooks/useBoardingPassData.ts
  src/app/mypage/shuttle/reservation/[reservationId]/components/Content.tsx
Labels: ✨ feat

#677 feat: 모든 try catch문에 sentry capture exception 추가
  sentry.edge.config.ts
  sentry.server.config.ts
  src/app/(home)/@greeting/page.tsx
  src/app/auth/identity-verification/page.tsx
  src/app/auth/login/[oauth]/page.tsx
  src/app/error.tsx
  src/app/event/[eventId]/components/handy-party/components/steps/MapStep.tsx
  src/app/event/[eventId]/components/shuttle-route-detail-view/components/KakaoMap.tsx
  src/app/event/[eventId]/components/steps/components/RequestSeatAlarmButton.tsx
  src/app/event/[eventId]/components/steps/demand-steps/DemandHubInfoStep.tsx
  src/app/event/[eventId]/components/steps/extra-steps/ExtraRealNameInputStep.tsx
  src/app/event/[eventId]/dailyevent/[dailyEventId]/route/[shuttleRouteId]/payment/components/Content.tsx
  src/app/event/[eventId]/dailyevent/[dailyEventId]/route/[shuttleRouteId]/payment/request/page.tsx
  src/app/mypage/alert-requests/components/AlertRequestCard.tsx
  src/app/mypage/coupons/components/RegisterCoupon.tsx
  src/app/mypage/reviews/edit/[reviewId]/components/ReviewEditForm.tsx
  src/app/mypage/reviews/write/[reservationId]/components/ReviewWriteForm.tsx
  src/app/mypage/shuttle/reservation/[reservationId]/components/sections/refund-section/components/CancelBottomSheet.tsx
  src/app/not-found.tsx
  src/components/feedback/FeedbackScreen.tsx
  src/components/kakao-map/KakaoMap.tsx
  src/hooks/analytics/useShareTracking.ts
  src/hooks/useNotFoundTracking.ts
  src/hooks/useTossPayments.tsx
  src/instrumentation-client.ts
  src/services/config.ts
Labels: ✨ feat

#685 fix: 상품별(셔틀버스) 유의사항 업데이트, 후기보기 플로팅버튼삭제
  src/components/dead-zone/DeadZonePopup.tsx
  src/components/guidelines/contents/Notice.tsx
Labels: 🐛 fix

#684 release: V2
  sentry.edge.config.ts
  sentry.server.config.ts
  src/app/(home)/@greeting/page.tsx
  src/app/auth/identity-verification/page.tsx
  src/app/auth/login/[oauth]/page.tsx
  src/app/error.tsx
  src/app/event/[eventId]/components/handy-party/components/steps/MapStep.tsx
  src/app/event/[eventId]/components/shuttle-route-detail-view/components/KakaoMap.tsx
  src/app/event/[eventId]/components/steps/components/RequestSeatAlarmButton.tsx
  src/app/event/[eventId]/components/steps/demand-steps/DemandHubInfoStep.tsx
  src/app/event/[eventId]/components/steps/extra-steps/ExtraRealNameInputStep.tsx
  src/app/event/[eventId]/dailyevent/[dailyEventId]/route/[shuttleRouteId]/payment/components/Content.tsx
  src/app/event/[eventId]/dailyevent/[dailyEventId]/route/[shuttleRouteId]/payment/request/[reservationId]/page.tsx
  src/app/event/[eventId]/dailyevent/[dailyEventId]/route/[shuttleRouteId]/payment/request/page.tsx
  src/app/mypage/alert-requests/components/AlertRequestCard.tsx
  src/app/mypage/boarding-pass/hooks/useBoardingPassData.ts
  src/app/mypage/coupons/components/RegisterCoupon.tsx
  src/app/mypage/reviews/edit/[reviewId]/components/ReviewEditForm.tsx
  src/app/mypage/reviews/write/[reservationId]/components/ReviewWriteForm.tsx
  src/app/mypage/shuttle/reservation/[reservationId]/components/Content.tsx
  src/app/mypage/shuttle/reservation/[reservationId]/components/sections/refund-section/components/CancelBottomSheet.tsx
  src/app/not-found.tsx
  src/components/dead-zone/DeadZonePopup.tsx
  src/components/feedback/FeedbackScreen.tsx
  src/components/guidelines/contents/Notice.tsx
  src/components/kakao-map/KakaoMap.tsx
  src/hooks/analytics/useShareTracking.ts
  src/hooks/useNotFoundTracking.ts
  src/hooks/useTossPayments.tsx
  src/instrumentation-client.ts
  src/services/config.ts
Labels: 🔖 release, ✨ feat, 🐛 fix, 🔥 hotfix

#686 fix: 명동합정 노선 옵챗 추가 및 reservation card 에도 반영
  src/app/event/[eventId]/dailyevent/[dailyEventId]/route/[shuttleRouteId]/payment/request/[reservationId]/page.tsx
  src/app/mypage/boarding-pass/hooks/useBoardingPassData.ts
  src/app/mypage/shuttle/components/reservations/reservation-card/components/ChatButton.tsx
  src/app/mypage/shuttle/reservation/[reservationId]/components/Content.tsx
  src/hooks/useTempSeventeen.ts
Labels: 🐛 fix

#687 release: V2
  src/app/event/[eventId]/dailyevent/[dailyEventId]/route/[shuttleRouteId]/payment/request/[reservationId]/page.tsx
  src/app/mypage/boarding-pass/hooks/useBoardingPassData.ts
  src/app/mypage/shuttle/components/reservations/reservation-card/components/ChatButton.tsx
  src/app/mypage/shuttle/reservation/[reservationId]/components/Content.tsx
  src/hooks/useTempSeventeen.ts
Labels: 🔖 release

#688 design: 핸디버스 가이드 문구 추가
  src/app/help/handybus-guide/page.tsx
Labels: 🎨 design

#682 fix: 가는편 오는편 용어를 행사장행 귀가행으로 변경
  docs/DEMAND_TRACKING.md
  docs/RESERVATION_TRACKING.md
  src/app/event/[eventId]/components/handy-party/components/SimpleRouteInfo.tsx
  src/app/event/[eventId]/components/handy-party/components/steps/ReservationInfoStep.tsx
  src/app/event/[eventId]/components/shuttle-route-detail-view/ShuttleRouteDetailView.tsx
  src/app/event/[eventId]/components/steps/components/SimpleRouteInfo.tsx
  src/app/event/[eventId]/components/steps/extra-steps/ExtraDuplicateHubStep.tsx
  src/app/event/[eventId]/components/steps/reservation-steps/ReservationHubsStep.tsx
  src/app/event/[eventId]/components/steps/reservation-steps/ReservationInfoStep.tsx
  src/app/event/[eventId]/dailyevent/[dailyEventId]/route/[shuttleRouteId]/payment/components/Content.tsx
  src/app/event/[eventId]/dailyevent/[dailyEventId]/route/[shuttleRouteId]/payment/components/sections/PriceSection.tsx
  src/app/event/[eventId]/dailyevent/[dailyEventId]/route/[shuttleRouteId]/payment/components/sections/ShuttleRouteInfoSection.tsx
  src/app/mypage/alert-requests/[alertRequestId]/components/section/ShuttleRouteInfoSection.tsx
  src/app/mypage/boarding-pass/page.tsx
  src/app/mypage/shuttle/hooks/useReservationProgress.ts
  src/constants/common.ts
  src/constants/status.ts
  src/data/faq/boarding-5.mdx
  src/types/shuttleRoute.type.ts
Labels: 🐛 fix

#689 release: V2
  docs/DEMAND_TRACKING.md
  docs/RESERVATION_TRACKING.md
  src/app/event/[eventId]/components/handy-party/components/SimpleRouteInfo.tsx
  src/app/event/[eventId]/components/handy-party/components/steps/ReservationInfoStep.tsx
  src/app/event/[eventId]/components/shuttle-route-detail-view/ShuttleRouteDetailView.tsx
  src/app/event/[eventId]/components/steps/components/SimpleRouteInfo.tsx
  src/app/event/[eventId]/components/steps/extra-steps/ExtraDuplicateHubStep.tsx
  src/app/event/[eventId]/components/steps/reservation-steps/ReservationHubsStep.tsx
  src/app/event/[eventId]/components/steps/reservation-steps/ReservationInfoStep.tsx
  src/app/event/[eventId]/dailyevent/[dailyEventId]/route/[shuttleRouteId]/payment/components/Content.tsx
  src/app/event/[eventId]/dailyevent/[dailyEventId]/route/[shuttleRouteId]/payment/components/sections/PriceSection.tsx
  src/app/event/[eventId]/dailyevent/[dailyEventId]/route/[shuttleRouteId]/payment/components/sections/ShuttleRouteInfoSection.tsx
  src/app/help/handybus-guide/page.tsx
  src/app/mypage/alert-requests/[alertRequestId]/components/section/ShuttleRouteInfoSection.tsx
  src/app/mypage/boarding-pass/page.tsx
  src/app/mypage/shuttle/hooks/useReservationProgress.ts
  src/constants/common.ts
  src/constants/status.ts
  src/data/faq/boarding-5.mdx
  src/types/shuttleRoute.type.ts
Labels: 🔖 release

#692 feat: 예약 양도 승인하기 페이지 기초 구현
  src/app/received-reservation/[token]/page.tsx
  src/services/reservationTransferRequest.service.ts
  src/types/reservation.type.ts
  src/types/reservationTransferRequest.type.ts
Labels: ✨ feat

#693 feat: 후기 작성완료 페이지
  src/app/mypage/reviews/write/[reservationId]/complete/icons/review-complete.svg
  src/app/mypage/reviews/write/[reservationId]/complete/page.tsx
  src/app/mypage/reviews/write/[reservationId]/components/ReviewWriteForm.tsx
  src/services/review.service.ts
Labels: ✨ feat

#695 feat: 예약상세에서 수수료 100% 환불인경우 ui 업데이트, 결제페이지/예약상세에서 핸디 관련문구 삭제
  src/app/event/[eventId]/dailyevent/[dailyEventId]/route/[shuttleRouteId]/payment/components/Content.tsx
  src/app/event/[eventId]/dailyevent/[dailyEventId]/route/[shuttleRouteId]/payment/components/sections/HandySection.tsx
  src/app/mypage/shuttle/hooks/useReservationProgress.ts
  src/app/mypage/shuttle/reservation/[reservationId]/components/Content.tsx
  src/app/mypage/shuttle/reservation/[reservationId]/components/sections/handy-section/HandySection.tsx
  src/app/mypage/shuttle/reservation/[reservationId]/components/sections/handy-section/components/CancelHandyApplyModal.tsx
  src/app/mypage/shuttle/reservation/[reservationId]/components/sections/handy-section/hooks/useCancelApplyHandy.tsx
  src/app/mypage/shuttle/reservation/[reservationId]/components/sections/price-section/components/RefundPriceContent.tsx
  src/app/mypage/shuttle/reservation/[reservationId]/components/sections/price-section/components/RefundRequestList.tsx
Labels: ✨ feat

#697 feat: 예약상세 - 지도 및 로드뷰 미리보기에 핸디팟 케이스 대응, 후기 로딩 ui 여백 추가
  src/app/mypage/reviews/components/WritableReviews.tsx
  src/app/mypage/reviews/components/WrittenReviews.tsx
  src/app/mypage/shuttle/reservation/[reservationId]/components/sections/shuttle-info-section/ShuttleInfoSection.tsx
  src/app/mypage/shuttle/reservation/[reservationId]/components/sections/shuttle-info-section/components/HubItem.tsx
  src/app/mypage/shuttle/reservation/[reservationId]/components/sections/shuttle-info-section/components/TripCard.tsx
  src/components/loading/Loading.tsx
Labels: ✨ feat, 🎨 design

#701 feat: 예약취소, 셔틀 종료 상태에서는 예약 상세 페이지 모달 방지
  src/app/mypage/shuttle/reservation/[reservationId]/components/FirstVisitModal.tsx
  src/app/mypage/shuttle/reservation/[reservationId]/page.tsx
Labels: ✨ feat

#711 fix: 결제 금액 계산 로직 수정
  src/utils/event.util.ts
Labels: 🐛 fix

#712 release: V2
  src/app/event/[eventId]/dailyevent/[dailyEventId]/route/[shuttleRouteId]/payment/components/Content.tsx
  src/app/event/[eventId]/dailyevent/[dailyEventId]/route/[shuttleRouteId]/payment/components/payment-guidelines/HandyPartyGuideline.tsx
  src/app/event/[eventId]/dailyevent/[dailyEventId]/route/[shuttleRouteId]/payment/components/payment-guidelines/ShuttleBusGuideline.tsx
  src/app/event/[eventId]/dailyevent/[dailyEventId]/route/[shuttleRouteId]/payment/components/sections/EventInfoSection.tsx
  src/app/event/[eventId]/dailyevent/[dailyEventId]/route/[shuttleRouteId]/payment/components/sections/GuidelineSection.tsx
  src/hooks/useScrollToBottom.tsx
  src/utils/event.util.ts
Labels: 🔖 release

#715 design: 결제 유의사항에 별 추가
  src/app/event/[eventId]/dailyevent/[dailyEventId]/route/[shuttleRouteId]/payment/components/payment-guidelines/HandyPartyGuideline.tsx
  src/app/event/[eventId]/dailyevent/[dailyEventId]/route/[shuttleRouteId]/payment/components/payment-guidelines/ShuttleBusGuideline.tsx
Labels: 🎨 design

#716 fix: 로드뷰 줌, 세로각도(tilt) 반영 및 예약취소/셔틀종료 예약내역에서 모달이 뜨던 이슈 해결
  src/app/mypage/shuttle/reservation/[reservationId]/components/sections/shuttle-info-section/ShuttleInfoSection.tsx
  src/app/mypage/shuttle/reservation/[reservationId]/components/sections/shuttle-info-section/components/Roadview.tsx
  src/app/mypage/shuttle/reservation/[reservationId]/page.tsx
Labels: 🐛 fix

#719 feat: 결제 유의사항 미확인 시 에러 토스트 및 스크롤
  src/app/event/[eventId]/components/steps/demand-steps/DemandHubsStep.tsx
  src/app/event/[eventId]/dailyevent/[dailyEventId]/route/[shuttleRouteId]/payment/components/Content.tsx
  src/app/event/[eventId]/dailyevent/[dailyEventId]/route/[shuttleRouteId]/payment/components/sections/PaymentSection.tsx
Labels: ✨ feat

#721 release: V2
  src/app/(home)/@event/components/RecommendedEventSwiperView.tsx
  src/app/(home)/@event/components/TrendEventsSwiperView.tsx
  src/app/(home)/@event/page.tsx
  src/app/(home)/@modal/components/EventPromotionModal.tsx
  src/app/(home)/@modal/images/event-promotion-modal-image-muse.png
  src/app/(home)/@modal/page.tsx
  src/app/event/[eventId]/components/steps/demand-steps/DemandHubsStep.tsx
  src/app/event/[eventId]/dailyevent/[dailyEventId]/route/[shuttleRouteId]/payment/components/Content.tsx
  src/app/event/[eventId]/dailyevent/[dailyEventId]/route/[shuttleRouteId]/payment/components/sections/PaymentSection.tsx
  src/app/event/page.tsx
  src/utils/localStorage.ts
Labels: 🔖 release

#722 fix: 토스 페이먼츠 스크립트 로드 안정화
  src/app/event/[eventId]/dailyevent/[dailyEventId]/route/[shuttleRouteId]/payment/components/Content.tsx
  src/app/event/[eventId]/dailyevent/[dailyEventId]/route/[shuttleRouteId]/payment/components/sections/GuidelineSection.tsx
  src/app/event/[eventId]/dailyevent/[dailyEventId]/route/[shuttleRouteId]/payment/page.tsx
  src/components/script/TossPaymentsScript.tsx
  src/hooks/useTossPayments.tsx
  src/types/coupon.type.ts
Labels: 🐛 fix

#727 chore: 개인정보약관 및 마케팅활용동의 업데이트
  src/components/footer/Footer.tsx
  src/data/policy/marketing.mdx
  src/data/policy/privacy.mdx
Labels: 🧹 chore
