Repository HandyBus/handybus-web-latest, pull requests merged in 2025-08, with the labels that each got.

#615 feat: 예약 취소 사유 모달
  src/app/mypage/shuttle/reservation/[reservationId]/components/Content.tsx
  src/app/mypage/shuttle/reservation/[reservationId]/components/sections/ReservationPersonInfoSection.tsx
  src/app/mypage/shuttle/reservation/[reservationId]/components/sections/refund-section/RefundSection.tsx
  src/app/mypage/shuttle/reservation/[reservationId]/components/sections/refund-section/components/CancelBottomSheet.tsx
  src/app/mypage/shuttle/reservation/[reservationId]/components/sections/refund-section/components/RadioInputGroup.tsx
  src/app/mypage/shuttle/reservation/[reservationId]/components/sections/refund-section/const/refund.const.ts
  src/app/mypage/shuttle/reservation/[reservationId]/components/sections/refund-section/hooks/useBottomSheetText.ts
  src/app/mypage/shuttle/reservation/[reservationId]/components/sections/refund-section/hooks/useHistory.tsx
  src/app/mypage/shuttle/reservation/[reservationId]/components/sections/refund-section/utils/createFeedbackContent.util.ts
  src/types/reservation.type.ts
Labels: ✨ feat

#617 fix: 예약 취소 모달 기타 input 사용성 개선
  src/app/mypage/shuttle/reservation/[reservationId]/components/sections/refund-section/components/RadioInputGroup.tsx
Labels: 🐛 fix

#618 release: V2
  src/app/(home)/@modal/components/OneDayModal.tsx
  src/app/(home)/@modal/images/coupon-event.png
  src/app/(home)/@modal/page.tsx
  src/app/demand-reward-coupon/images/coupon-event-info.png
  src/app/demand-reward-coupon/page.tsx
  src/app/mypage/shuttle/reservation/[reservationId]/components/Content.tsx
  src/app/mypage/shuttle/reservation/[reservationId]/components/sections/ReservationPersonInfoSection.tsx
  src/app/mypage/shuttle/reservation/[reservationId]/components/sections/refund-section/RefundSection.tsx
  src/app/mypage/shuttle/reservation/[reservationId]/components/sections/refund-section/components/CancelBottomSheet.tsx
  src/app/mypage/shuttle/reservation/[reservationId]/components/sections/refund-section/components/RadioInputGroup.tsx
  src/app/mypage/shuttle/reservation/[reservationId]/components/sections/refund-section/const/refund.const.ts
  src/app/mypage/shuttle/reservation/[reservationId]/components/sections/refund-section/hooks/useBottomSheetText.ts
  src/app/mypage/shuttle/reservation/[reservationId]/components/sections/refund-section/hooks/useHistory.tsx
  src/app/mypage/shuttle/reservation/[reservationId]/components/sections/refund-section/utils/createFeedbackContent.util.ts
  src/types/reservation.type.ts
Labels: 🔖 release

#619 feat: 애플 로그인 기초 구현
  package-lock.json
  package.json
  src/app/auth/login/[oauth]/page.tsx
  src/app/layout.tsx
  src/app/login/icons/apple.svg
  src/app/login/page.tsx
  src/services/auth.service.ts
  src/utils/localStorage.ts
Labels: ✨ feat

#620 feat: 핸디삭제, 오픈채팅방 정책변경, 탑승권 추가
  src/app/event/[eventId]/dailyevent/[dailyEventId]/route/[shuttleRouteId]/payment/components/Content.tsx
  src/app/event/[eventId]/dailyevent/[dailyEventId]/route/[shuttleRouteId]/payment/components/sections/HandySection.tsx
  src/app/event/[eventId]/dailyevent/[dailyEventId]/route/[shuttleRouteId]/payment/components/sections/PriceSection.tsx
  src/app/event/[eventId]/dailyevent/[dailyEventId]/route/[shuttleRouteId]/payment/request/[reservationId]/page.tsx
  src/app/help/about/images/service-overview-2.png
  src/app/help/faq/components/FAQList.tsx
  src/app/help/faq/direct-inquiry/page.tsx
  src/app/help/faq/page.tsx
  src/app/help/handybus-guide/images/handybus-guide-step-4.png
  src/app/help/handybus-guide/page.tsx
  src/app/help/what-is-handy/components/WhatIsHandyContent.tsx
  src/app/help/what-is-handy/images/bottom.png
  src/app/help/what-is-handy/images/coupon.png
  src/app/help/what-is-handy/images/description-1.png
  src/app/help/what-is-handy/images/description-2.png
  src/app/help/what-is-handy/images/description-3.png
  src/app/help/what-is-handy/images/description-4.png
  src/app/help/what-is-handy/images/main.png
  src/app/help/what-is-handy/page.tsx
  src/app/mypage/boarding-pass/icons/dot-primary.svg
  src/app/mypage/boarding-pass/icons/pin-primary.svg
  src/app/mypage/boarding-pass/icons/white-arrow-right.svg
  src/app/mypage/boarding-pass/page.tsx
  src/app/mypage/components/Settings.tsx
  src/app/mypage/shuttle/components/reservations/reservation-card/ReservationCard.tsx
  src/app/mypage/shuttle/components/reservations/reservation-card/components/ChatButton.tsx
  src/app/mypage/shuttle/components/reservations/reservation-card/components/HandyBadge.tsx
  src/app/mypage/shuttle/components/reservations/reservation-card/hooks/useTextAndStyle.ts
  src/app/mypage/shuttle/reservation/[reservationId]/components/Content.tsx
  src/app/mypage/shuttle/reservation/[reservationId]/components/sections/handy-section/HandySection.tsx
  src/app/mypage/shuttle/reservation/[reservationId]/components/sections/price-section/PriceSection.tsx
  src/app/mypage/shuttle/reservation/[reservationId]/components/sections/price-section/components/RegularPriceContent.tsx
  src/app/mypage/shuttle/reservation/[reservationId]/components/sections/refund-section/RefundSection.tsx
  src/app/mypage/shuttle/reservation/[reservationId]/components/sections/shuttle-progress-section/HandyPartyProgressSection.tsx
  src/app/mypage/shuttle/reservation/[reservationId]/components/sections/shuttle-progress-section/ShuttleProgressSection.tsx
  src/app/sitemap.ts
  src/constants/common.ts
  src/data/faq/boarding-1.mdx
  src/data/faq/boarding-2.mdx
  src/data/faq/boarding-3.mdx
  src/data/faq/boarding-4.mdx
  src/data/faq/boarding-5.mdx
  src/data/faq/boarding-6.mdx
  src/data/faq/boarding-7.mdx
  src/data/faq/etc-1.mdx
  src/data/faq/index.tsx
  tailwind.config.ts
Labels: ✨ feat

#623 release: V2
  package-lock.json
  package.json
  src/app/auth/login/[oauth]/page.tsx
  src/app/event/[eventId]/dailyevent/[dailyEventId]/route/[shuttleRouteId]/payment/components/Content.tsx
  src/app/event/[eventId]/dailyevent/[dailyEventId]/route/[shuttleRouteId]/payment/components/sections/HandySection.tsx
  src/app/event/[eventId]/dailyevent/[dailyEventId]/route/[shuttleRouteId]/payment/components/sections/PriceSection.tsx
  src/app/event/[eventId]/dailyevent/[dailyEventId]/route/[shuttleRouteId]/payment/request/[reservationId]/page.tsx
  src/app/help/about/images/service-overview-2.png
  src/app/help/faq/components/FAQList.tsx
  src/app/help/faq/direct-inquiry/page.tsx
  src/app/help/faq/page.tsx
  src/app/help/handybus-guide/images/handybus-guide-step-4.png
  src/app/help/handybus-guide/page.tsx
  src/app/help/what-is-handy/components/WhatIsHandyContent.tsx
  src/app/help/what-is-handy/images/bottom.png
  src/app/help/what-is-handy/images/coupon.png
  src/app/help/what-is-handy/images/description-1.png
  src/app/help/what-is-handy/images/description-2.png
  src/app/help/what-is-handy/images/description-3.png
  src/app/help/what-is-handy/images/description-4.png
  src/app/help/what-is-handy/images/main.png
  src/app/help/what-is-handy/page.tsx
  src/app/layout.tsx
  src/app/login/icons/apple.svg
  src/app/login/page.tsx
  src/app/mypage/boarding-pass/icons/dot-primary.svg
  src/app/mypage/boarding-pass/icons/pin-primary.svg
  src/app/mypage/boarding-pass/icons/white-arrow-right.svg
  src/app/mypage/boarding-pass/page.tsx
  src/app/mypage/components/Settings.tsx
  src/app/mypage/settings/page.tsx
  src/app/mypage/shuttle/components/reservations/reservation-card/ReservationCard.tsx
  src/app/mypage/shuttle/components/reservations/reservation-card/components/ChatButton.tsx
  src/app/mypage/shuttle/components/reservations/reservation-card/components/HandyBadge.tsx
  src/app/mypage/shuttle/components/reservations/reservation-card/hooks/useTextAndStyle.ts
  src/app/mypage/shuttle/reservation/[reservationId]/components/Content.tsx
  src/app/mypage/shuttle/reservation/[reservationId]/components/sections/handy-section/HandySection.tsx
  src/app/mypage/shuttle/reservation/[reservationId]/components/sections/price-section/PriceSection.tsx
  src/app/mypage/shuttle/reservation/[reservationId]/components/sections/price-section/components/RegularPriceContent.tsx
  src/app/mypage/shuttle/reservation/[reservationId]/components/sections/refund-section/RefundSection.tsx
  src/app/mypage/shuttle/reservation/[reservationId]/components/sections/shuttle-progress-section/HandyPartyProgressSection.tsx
  src/app/mypage/shuttle/reservation/[reservationId]/components/sections/shuttle-progress-section/ShuttleProgressSection.tsx
  src/app/sitemap.ts
  src/constants/common.ts
  src/data/faq/boarding-1.mdx
  src/data/faq/boarding-2.mdx
  src/data/faq/boarding-3.mdx
  src/data/faq/boarding-4.mdx
  src/data/faq/boarding-5.mdx
  src/data/faq/boarding-6.mdx
  src/data/faq/boarding-7.mdx
  src/data/faq/etc-1.mdx
  src/data/faq/index.tsx
  src/services/auth.service.ts
  src/types/user.type.ts
  src/utils/localStorage.ts
  tailwind.config.ts
Labels: 🔖 release

#625 feat: 예약완료페이지에 공지방 링크 반영, 핸디팟은 기본 페이지처리
  src/app/event/[eventId]/dailyevent/[dailyEventId]/route/[shuttleRouteId]/payment/request/[reservationId]/page.tsx
Labels: ✨ feat

#631 release: V2
  src/app/(home)/@event/components/PinnedEventCard.tsx
  src/app/(home)/@event/components/RecommendedEventSwiperView.tsx
  src/app/(home)/@event/components/TrendEventCard.tsx
  src/app/(home)/@event/components/TrendEventsSwiperView.tsx
  src/app/(home)/@event/page.tsx
  src/app/event/[eventId]/components/EventContent.tsx
  src/app/event/[eventId]/components/EventInfo.tsx
  src/app/event/[eventId]/components/event-form/EventForm.tsx
  src/app/event/[eventId]/components/event-form/hooks/useEventInitialization.tsx
  src/app/event/[eventId]/dailyevent/[dailyEventId]/route/[shuttleRouteId]/payment/components/Content.tsx
  src/app/event/[eventId]/dailyevent/[dailyEventId]/route/[shuttleRouteId]/payment/components/sections/EventInfoSection.tsx
  src/app/event/[eventId]/store/eventAtom.ts
  src/app/event/page.tsx
  src/app/event/toSorted.util.ts
  src/app/sitemap.ts
  src/services/event.service.ts
  src/types/event.type.ts
  src/utils/event.util.ts
Labels: 🔖 release

#632 fix: 탑승인원 표기 및 데이터 검증 로직 추가, 결제페이지 쿠폰 리스트 스크롤
  src/app/event/[eventId]/dailyevent/[dailyEventId]/route/[shuttleRouteId]/payment/components/sections/CouponSection.tsx
  src/app/mypage/boarding-pass/hooks/useBoardingPassData.ts
  src/app/mypage/boarding-pass/page.tsx
Labels: 🐛 fix

#638 release: V2
  src/app/event/[eventId]/components/steps/reservation-steps/ReservationHubsStep.tsx
  src/app/event/[eventId]/store/dailyEventIdsWithHubsAtom.ts
  src/utils/event.util.ts
Labels: 🔖 release

#647 style: 결제 완료시 공지방링크 없으면 공지방 가리기
  src/app/event/[eventId]/dailyevent/[dailyEventId]/route/[shuttleRouteId]/payment/request/[reservationId]/page.tsx
Labels: 🖋️ style

#648 release: V2
  docs/RESERVATION_TRACKING.md
  src/app/event/[eventId]/components/event-form/EventForm.tsx
  src/app/event/[eventId]/components/event-form/components/BottomBar.tsx
  src/app/event/[eventId]/components/handy-party/components/steps/AddressStep.tsx
  src/app/event/[eventId]/components/handy-party/components/steps/MapStep.tsx
  src/app/event/[eventId]/components/handy-party/components/steps/ReservationInfoStep.tsx
  src/app/event/[eventId]/components/handy-party/components/steps/TripTypeStep.tsx
  src/app/event/[eventId]/components/steps/common-steps/CommonSidoStep.tsx
  src/app/event/[eventId]/components/steps/extra-steps/ExtraRealNameInputStep.tsx
  src/app/event/[eventId]/components/steps/reservation-steps/ReservationInfoStep.tsx
  src/app/event/[eventId]/dailyevent/[dailyEventId]/route/[shuttleRouteId]/payment/components/Content.tsx
  src/app/event/[eventId]/dailyevent/[dailyEventId]/route/[shuttleRouteId]/payment/page.tsx
  src/app/event/[eventId]/dailyevent/[dailyEventId]/route/[shuttleRouteId]/payment/payment.const.ts
  src/app/event/[eventId]/dailyevent/[dailyEventId]/route/[shuttleRouteId]/payment/request/[reservationId]/page.tsx
  src/app/event/[eventId]/dailyevent/[dailyEventId]/route/[shuttleRouteId]/payment/request/page.tsx
  src/app/mypage/boarding-pass/page.tsx
  src/app/mypage/shuttle/components/reservations/reservation-card/components/ChatButton.tsx
  src/app/mypage/shuttle/reservation/[reservationId]/components/Content.tsx
  src/components/guidelines/contents/Notice.tsx
  src/data/faq/reservation-10.mdx
  src/data/faq/reservation-9.mdx
  src/hooks/analytics/store/reservationTracking.store.ts
  src/hooks/analytics/useDemandTracking.ts
  src/hooks/analytics/useReservationTracking.ts
  src/hooks/analytics/useReservationTrackingGlobal.ts
  src/hooks/useTossPayments.tsx
  src/utils/analytics/reservationAnalytics.util.ts
Labels: 🔖 release

#652 release: V2
  src/app/event/[eventId]/components/steps/common-steps/CommonSidoStep.tsx
  src/app/event/[eventId]/components/steps/extra-steps/ExtraDuplicateHubStep.tsx
Labels: 🔖 release

#654 feat: 유저 에러 모니터링 툴 (Sentry) 설치
  .cursor/mcp.json
  .cursor/rules/sentry.mdc
  next.config.mjs
  package-lock.json
  package.json
  sentry.edge.config.ts
  sentry.server.config.ts
  src/app/error.tsx
  src/app/layout.tsx
  src/instrumentation-client.ts
  src/instrumentation.ts
Labels: ✨ feat

#656 design: 애플 로그인 배지
  package-lock.json
  src/app/mypage/settings/page.tsx
Labels: 🎨 design

#658 design: 핸디버스 소개 이미지 수정
  src/app/help/about/images/service-overview-2.png
Labels: 🎨 design

#659 style: 약관에 오타수정
  src/components/guidelines/contents/Demand.tsx
Labels: 🖋️ style

#664 feat: 복수 노선 뷰에서 가는편의 경우 도착 시간 표시
  src/app/event/[eventId]/components/steps/extra-steps/ExtraDuplicateHubStep.tsx
Labels: ✨ feat

#665 release: V2
  src/app/event/[eventId]/components/steps/extra-steps/ExtraDuplicateHubStep.tsx
Labels: 🔖 release

#666 chore: 서버 점검 적용
  src/app/layout.tsx
  src/components/service-maintenance-screen/ServiceMaintenanceScreen.tsx
Labels: 🧹 chore

#668 chore: 서버 점검 해제
  src/app/layout.tsx
Labels: 🧹 chore

#669 release: V2
  src/app/layout.tsx
Labels: 🔖 release

#673 feat: 데이식스 이벤트 페이지
  src/app/user-events/202508/day-6/icons/doc-icon.svg
  src/app/user-events/202508/day-6/page.tsx
Labels: ✨ feat

#674 release: V2
  src/app/mypage/boarding-pass/page.tsx
  src/app/mypage/reviews/components/WritableReviews.tsx
  src/app/mypage/reviews/components/WrittenReviews.tsx
  src/app/mypage/reviews/components/reservation-card/ReservationCardForReview.tsx
  src/app/mypage/reviews/components/reservation-card/ReviewButton.tsx
  src/app/mypage/reviews/components/reservation-card/hooks/useTextAndStyleForReview.ts
  src/app/mypage/reviews/edit/[reviewId]/page.tsx
  src/app/mypage/reviews/write/[reservationId]/page.tsx
  src/app/mypage/shuttle/components/reservations/reservation-card/ReservationCard.tsx
  src/app/mypage/shuttle/components/reservations/reservation-card/components/ChatButton.tsx
  src/app/mypage/shuttle/components/reservations/reservation-card/hooks/useTextAndStyle.ts
  src/app/mypage/shuttle/hooks/useReservationProgress.ts
  src/app/mypage/shuttle/reservation/[reservationId]/components/Content.tsx
  src/app/mypage/shuttle/reservation/[reservationId]/components/sections/shuttle-progress-section/HandyPartyProgressSection.tsx
  src/app/mypage/shuttle/reservation/[reservationId]/components/sections/shuttle-progress-section/hooks/useHandyPartyProgressText.tsx
  src/app/mypage/shuttle/reservation/[reservationId]/components/sections/shuttle-progress-section/hooks/useText.tsx
  src/app/user-events/202508/day-6/icons/doc-icon.svg
  src/app/user-events/202508/day-6/page.tsx
  src/services/reservation.service.ts
Labels: 🔖 release

#676 feat: 리뷰 및 프로필 사진 업로드 시 크기 압축
  package-lock.json
  package.json
  src/app/mypage/profile/edit/components/EditForm.tsx
  src/app/mypage/reviews/write/[reservationId]/components/ReviewWriteForm.tsx
  src/app/mypage/reviews/write/[reservationId]/page.tsx
Labels: ✨ feat

#678 release: V2
  package-lock.json
  package.json
  src/app/mypage/profile/edit/components/EditForm.tsx
  src/app/mypage/reviews/write/[reservationId]/components/ReviewWriteForm.tsx
  src/app/mypage/reviews/write/[reservationId]/page.tsx
  src/app/mypage/shuttle/components/reservations/reservation-card/components/ChatButton.tsx
Labels: 🔖 release
